### ISSUE TITLE
[BUG] UI general fixes

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#109]
### This issue will be part of ODHack8.0, please apply via Onlydust app
- Fix the form label to only allow numbers, for the set stark goal label in (frontend/gostarkme-web/components/modules/newfunding/FundingStep.tsx).
- Add back button in new fund fase 2 page, this will help to return to fase 1 page, in case of need to change fund info (frontend/gostarkme-web/components/modules/newfunding/DescriptionStep.tsx).
- Add warning to form labels empty, for all the page forms.
- Fix discord link in the footer, link: https://discord.gg/sEpnC6JB2U 
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue.

**Comment by raizo07** [comment]
@adrianvrj can I work on this

**Comment by martinvibes** [comment]
can i work on this issue @adrianvrj

**Comment by coxmars** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I'm a software developer with 2+ years of experience and I have worked with backend technologies such as Cairo, Java, C# and frontend with React, NextJS, JS/TS. Also, I'm a member of the Dojo Coding community here in CR and I have made contributions in Cairo VM Go, Cairo VM TS, Cairo Lints etc.

### How I plan on tackling this issue
I’ll review the contributor guide and any existing components to ensure the correct behavior, I will apply this fix according with the requested changes and I already have experience with the project so this could be ready in 1-2 days as maximum.

**Comment by devcollinss** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
My name is Collins Ikechukwu. I'm a full stack blockchain developer developer.
I estimate this will take approximately 24 hours to complete.

### How I plan on tackling this issue


This is how I would tackle this issue:
1. **Fix Form Label**: Update the `FundingStep.tsx` file to restrict input for the set stark goal label to only allow numbers.
2. **Add Back Button**: In the `DescriptionStep.tsx` file, implement a back button that allows users to return to the first funding phase.
3. **Add Warnings for Empty Form Labels**: Implement warnings for empty form fields across all forms on the page.
4. **Fix Discord Link**: Update the footer to correct the Discord link to https://discord.gg/sEpnC6JB2U.

**Comment by sanieni6** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hi, Luis here, a frontend developer

### How I plan on tackling this issue
My approach will be as follows:
1. change this interface to ensure that only allows numbers:
interface FundingStepProps {
  fundingName: string;
  setFundingName: (name: string) => void;
  name: string;
  setName: (name: string) => void;
}
2. then, i will add a back button
3. Form safety, i am going to create a hook to handle empty form labels, (i highly recommend to use Zod library: https://zod.dev/
4.Fix the discord link

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hello @adrianvrj I'm a frontend and a blockchain developer. I will love to work on this, this is something I can do. please assign 

### How I plan on tackling this issue
Below is how I planto address it 
- I will ensure to read the contributors guide to comply with the project standards.
- I will update the form label in FundingStep.tsx to ensure it only allows numeric inputs for the Stark goal.
- I will implement a back button in the DescriptionStep.tsx to enable users to return to the previous phase for editing fund information.
- I will add warning messages for any empty form labels across all pages.
- I will correct the Discord link in the footer to the provided URL: https://discord.gg/sEpnC6JB2U.

**Comment by AnoukRImola** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hi, I'm Anouk Rímola and I'll be working on issue #109.

I estimate this will take 2 days to complete.

### How I plan on tackling this issue
- Validate "stark goal" input to allow only numbers.
- Add a "Back" button for navigation between fund phases.
- Implement empty label warnings for all forms.
- Fix Discord link in the footer :)

**Comment by MariangelaNM** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hello, I'm Mariangela. I'm a software developer specializing in front-end development.

### How I plan on tackling this issue
### **Step 1: Allow only numbers for "Set Stark Goal"**
 Update the input field with `type="number"` or use validation to accept only numbers.
 Test with valid and invalid inputs.

### **Step 2: Add back button in phase 2**
 Add a back button using `useRouter` to navigate to `/newfunding/step1`.
 Test the navigation.

### **Step 3: Add warnings for empty form labels**
 Add validation logic to check for empty fields and display warnings.
 Test form submission with empty fields.

### **Step 4: Fix Discord link**
 Update the Discord link to `https://discord.gg/sEpnC6JB2U`.
 Test the link.

**Comment by JosueBrenes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

Hi, I'm **Josué Brenes** and I'll be working on issue #109.

I estimate this will take **1 day** to complete.

## Approach to Tackling the Issue

Here’s how I would tackle this issue:

1. **Restrict Input Types**:  
   I will change the input type for the goal-setting field to `number` in the `FundingStep` component, ensuring that users can only enter numeric values. The code will look like this:

   ```tsx
   <input
     type="number" // Changed to 'number'
     placeholder="Set your goal in STRKs"
     value={name}
     onChange={(e) => setName(e.target.value)}
     className="mt-4 p-2 pl-4 border border-black rounded w-full placeholder:text-base"
     required
   />

2. **Add Back Button**:  
   I will implement a back button in the `DescriptionStep` component to allow users to navigate back to the previous step easily. The code for the button will be:

   ```tsx
   <button
     onClick={() => {/* logic to go back to the previous step */}}
     className="mt-4 p-2 border border-black rounded bg-gray-200"
   >
     Back
   </button>

3. **Validation and Warnings**:  
   To enhance the user experience, I will add validation to display warnings when form fields are empty. This could look like this:

   ```tsx
   const showWarning = !fundingDescription.trim();

   return (
     <div>
       {showWarning && <p className="text-red-500">Please fill out all fields.</p>}
       <textarea
         placeholder="Funding description"
         value={fundingDescription}
         onChange={(e) => setFundingDescription(e.target.value)}
         className="mt-3 p-4 border border-black rounded w-full h-60 resize-none"
         required
       />
     </div>
   );

4. **Fix Discord Link**:  
   I will ensure that the Discord link in the footer is accurate and functional, directing users to the correct server:

   ```html
   <footer>
     <a href="https://discord.com/invite/sEpnC6JB2U" target="_blank" rel="noopener noreferrer">Join our Discord</a>
   </footer>
