### ISSUE TITLE
[feat] Add connect wallet functionality 

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#110]
### This issue will be part of ODHack8.0, please apply via Onlydust app
- Add functionality to connect your starknet wallet, the page display the pop up and the user accept the terms and the wallet address will be return.
-  The connect wallet btn inside the app, should no longer be available, in its place, a partial string of the user's address should be displayed, ex: 0x123...321.
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue.

**Comment by Gift-Naomi** [comment]
@adrianvrj can I please work on this?

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
hello i would love to work on this

### How I plan on tackling this issue
please knidly assign :)

**Comment by devcollinss** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
My name is Collins Ikechukwu. I'm a full stack blockchain developer developer.
I estimate this will take approximately 24 hours to complete.

### How I plan on tackling this issue
This is how I would tackle this issue:
1. **Set Up Wallet Connection**: Implement the wallet connection using `starknet.js`.
2. **Popup Implementation**: Create a modal to display the terms and capture the wallet address.
3. **Update UI**: Replace the "Connect Wallet" button with a partial wallet address display.
4. **Testing**: Ensure functionality works as expected and the UI updates correctly.

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hello @adrianvrj I'm a frontend and a blockchain developer. I will love to work on this, kindly assign please 

### How I plan on tackling this issue
Here is how I plan to implement a solution:
- I will ensure to read the contributors guide to align with the project's standards.
- I will add functionality to connect the StarkNet wallet, including a pop-up for users to accept terms.
- Once connected, I will replace the connect wallet button with a partially masked wallet address (e.g., 0x131...271).

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I am a Full Stack Developer with extensive experience in blockchain development, specializing in Next.js, TypeScript, Node.js, and Rust. With over 18 contributions across projects in the OnlyDust ecosystem, I’ve developed a strong proficiency in delivering high-quality solutions and tackling complex issues under tight deadlines. My experience spans frontend, backend, smart contract development, and a deep understanding of optimizing and maintaining scalable codebases.

### How I plan on tackling this issue
To begin, I would implement the wallet connection using Starknet.js, enabling the user to connect their Starknet wallet via a popup. This popup will display the terms and conditions, which the user must accept to proceed with the wallet connection. Upon successful connection, the user's wallet address will be captured, and the "Connect Wallet" button will be replaced with a partial string of the wallet address (e.g., 0x123...321). This will ensure the wallet is connected and displayed correctly, while keeping the interface clean and informative. Lastly, I would test the flow to confirm that the connection is smooth and the address displays properly after connecting.

My ETA: 30hrs

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
i am a frontend and blockchain dev kindly assign please :)

### How I plan on tackling this issue
Implement Wallet Connection Functionality:

Create a function that triggers the wallet connection process when the user initiates the action.
Display a pop-up that outlines the terms of use for connecting the wallet. Ensure that users must accept these terms before proceeding.
Handle User Acceptance:

Once the user accepts the terms, retrieve the wallet address from the StarkNet wallet.
Ensure that the address is securely handled and stored.
Update UI:

Replace the existing "Connect Wallet" button in the app with a display of a partial string of the user's wallet address (e.g., 0x123...321).
Ensure the displayed address is formatted correctly and is visually distinct to indicate it’s a wallet address.
Testing:

Test the entire flow to ensure the pop-up appears correctly, the terms are displayed, and the wallet connects seamlessly.
Verify that the wallet address displays accurately in the UI after connection.

**Comment by MPSxDev** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hello, I am Manuel, a process engineer and web3 developer. I have participated in Starknet Bootcamps, ETHGlobal  and am an Elite winner of Speedrunstark. I have a high capacity to solve problems. I am a member of the `DojoCoding community.`
I hope this issue is assigned to me. I am available to work immediately to achieve what is required in the shortest time possible.


### How I plan on tackling this issue
### Steps to Add Starknet Wallet Connection

1. **Apply via Onlydust App:**
   - Submit your application for ODHack8.0 via the Onlydust app.

2. **Implement Wallet Connection:**
   - Add a button to connect the Starknet wallet.
   - Trigger a popup where the user accepts the terms of use.
   - Retrieve the wallet address once the user agrees.

3. **Replace Button with Partial Address:**
   - Replace the "Connect Wallet" button with a **partial wallet address** (`0x123...321`).

4. **Test and Submit:**
   - Test the functionality to ensure it's working properly.
   - Submit the final code after testing.

**Comment by jimenezz22** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I am an active member of the Dojo Coding community in Costa Rica, with experience in Cairo, having built onchain games like ByteBeasts and contributed to open-source projects such as CairoLint, where I implemented tests for Cairo lints. Additionally, I taught Cairo during the Starknet Bootcamp for Dojo Coding. I also have experience with TypeScript, contributing to Starknet Quest by developing components like ComboBoxes, among others.

### How I plan on tackling this issue
I would approach the problem by integrating Starknet.js to handle the wallet connection via a popup, where the user accepts terms and conditions. Once the wallet is connected, I'd capture the wallet address and replace the "Connect Wallet" button with a shortened version of the address (e.g., 0x123...321) for a cleaner interface. Finally, I would test the entire flow to ensure a smooth connection and correct address display.

Estimated time: 1-2 days

**Comment by jimenezz22** [comment]
thanks @adrianvrj for assigning me the issue, I will start working asap
