### ISSUE TITLE
[feat] Implement the STRK deposit when donating

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#121]
# User Story
As a user and donator, I want to deposit my STRKs into a funding in order to support a project or charity.

# Acceptance Criteria
- The STRKs are deducted from user's wallet.
- The funding contract should now have the original amount + deposited amount of STRKs.
- Anyone should be able to call this function but the owner.
- Tests should be added for this.

**Comment by limitlxx** [comment]
I'd like to contribute. Here's my approach 
1. Check wallet balance before invoking the fund function
2. The funding function should be able to get the amount sent, the contract balance and add them up then assign a new value to the contract balance 
3. I would add a component to checkIfOwner

**Comment by EmmanuelAR** [comment]
Yes!
