### ISSUE TITLE
Tests for funds contracts

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#13]
Add tests for all fund.cairo contract

**Comment by manlikeHB** [comment]
Hi @adrianvrj, can i work on this?

**Comment by adrianvrj** [comment]
Hi, unfortunately we don't have funds to pay our contributors for the moment, let me know if you still want to contribute!

**Comment by manlikeHB** [comment]
Thank you for letting me know @adrianvrj, I'm still interested in contributing to this project.

**Comment by adrianvrj** [comment]
you can work on it, I will assign you as soon as I can! If you have any doubts pls contact me

**Comment by adrianvrj** [comment]
@manlikeHB assigned!

**Comment by adrianvrj** [comment]
Hi @manlikeHB any updates from this?

**Comment by manlikeHB** [comment]
@adrianvrj, I'll open a PR tomorrow.

**Comment by adrianvrj** [comment]
We made some changes to the code you might want to checkout
