### ISSUE TITLE
[feat] Emit event when fund contract is deployed

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#136]
### This issue will be part of ODHack9.0, please apply via Onlydust app
- Emit an event when a fund contract is successfully deployed by the fund manager contract.
- The event should contain: the owner (caller address), the new fund contract address and the id.
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue

### Acceptance Criteria
- Code builds successfully.
- Event struct has all the attributes needed.

**Comment by martinvibes** [comment]
hello @adrianvrj i would like to work this 
kindly assign :)

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a Starknet Wolf. I am a software engineer at Invisible Studios, and a blockchain engineer with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum, Stellar ecosystem.


### How I plan on tackling this issue
To address this issue, I will add an event that gets emitted upon the successful deployment of the `Fund` contract. The event will include the owner (caller address), the new fund contract address, and the `id` of the fund. First, I will define an event structure that includes three fields: `owner`, `contract_address`, and `id`. During the execution of the constructor, after initializing the necessary contract state variables, I will emit this event using Starknet’s event emission functionality. The owner will be set as the caller (retrieved using `get_caller_address()`), the contract address will be the result of `get_contract_address()`, and the `id` will be passed to the constructor. Additionally, I will ensure that the emitted event includes the correct information, and I will write corresponding tests to confirm that the event is fired correctly when a new `Fund` contract is deployed.

ETA - 2 hours

**Comment by Mystic-Nayy** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I am a web3 developer, I have expertise in smart contracts, decentralized technologies, and frameworks like React. I can build innovative dApps, contribute to open-source projects, educate others, and network with industry leaders to advance my career in the decentralized space.

### How I plan on tackling this issue
i will Implement an event that emits when a fund contract is successfully deployed by the fund manager contract, including the owner (caller address), the new fund contract address, and the ID. Ensure the event struct includes all necessary attributes to fulfill the acceptance criteria. Verify that the code builds successfully and conduct tests to confirm that the event is emitted correctly upon contract deployment.

**Comment by anonfedora** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Template:
Hi, I'm Eleazar and I'll be working on issue #139.

I estimate this will take 5hours max to complete.

### How I plan on tackling this issue
This is how I would tackle this issue:

Review the implementation function and Event struct

Add attributes to the event as required

Ensure code builds successfully

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I am a blockchain developer with vast knowledge in languages as cairo, typescript, javascript, Html, Css , solidity, React etc. My background in smart contract development will help ensure this implementation is efficient and effective.

### How I plan on tackling this issue
To solve the issue of emitting an event when a fund contract is successfully deployed by the fund manager contract, I would create an event structure that includes the caller's address (owner), the newly deployed fund contract address, and the fund ID. In the fund manager contract, I would implement the logic to emit this event right after the fund contract is deployed. I will ensure that the code builds successfully and that the event struct captures all required attributes.

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to contribute. I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo.

### How I plan on tackling this issue
To solve this issue, I’ll take the following steps:
1.⁠ ⁠First, I’ll define the event (FundContractDeployed) in the fund manager contract.
2.⁠ ⁠⁠Then I’ll emit the event in the deployFundContract function after the contract is deployed.
3.⁠ ⁠⁠Next, I’ll ensure the contract compiles successfully.
4.⁠ ⁠⁠I’ll write and run tests to validate that the event is emitted correctly with all required attributes.
5.⁠ ⁠⁠Lastly, I’ll check test results to confirm that everything works as expected

Please assign me, I’m ready to work.

**Comment by saimeunt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I have contributed to several Cairo projects on OnlyDust and I've worked on very similar issues in the past such as https://github.com/ArkProjectNFTs/bridge/pull/236

### How I plan on tackling this issue
I will carefully add the necessary Starknet event and will make sure to emit it correctly where it is required.

**Comment by 0xprivateChaos** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I bring 2 years of hands-on experience in writing and optimizing tests for Solidity smart contracts, which has given me strong foundation in blockchain testing patterns. Recently, I've expanded my expertise into Cairo development, actively writing contracts and their corresponding tests. My combination of established testing experience in Solidity and fresh perspective in Cairo, along with deep theoretical knowledge of event handling and contract deployment workflows makes me well-suited to implement this fund deployment event feature.

### How I plan on tackling this issue
Implementation: Add FundCreated event to the fund manager contract that captures owner, fund address and id at deployment time

Modification: Update the fund deployment function to emit this event with required parameters once deployment succeeds

Testing: Create test scenarios to verify event emission with correct parameters during fund creation through manager contract

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I am a cairo dev. A new-comer here, willing and ready to contribute to contribute to solve the issue.
