### ISSUE TITLE
[fix] Fund's goal general fixes

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#140]
### This issue will be part of ODHack9.0, please apply via Onlydust app
- Create new minimum goal constant, (500).
- Add a new assert in ```newFund``` method (fund manager) that validates the input goal, should be greater or equal to the new constant.
- Add or modify tests to make sure functionality is working fine.
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue

### Acceptance Criteria
- New constant created.
- Assertion added to ```newFund``` method.
- Tests modified or added.
- All tests passing.

**Comment by Josue19-08** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
My name is Josué. I'm part of the Dojo Coding community and have worked on several projects, including some in Unity. I have experience with C#, .NET, Java, JavaScript, Angular, and Node.js. I love contributing to open-source projects, whether it's fixing bugs, adding new features, or improving documentation.


### How I plan on tackling this issue
I'll create a new constant for the minimum goal (500), add an assertion in the newFund method to validate it, and update the tests to ensure everything works correctly.

**Comment by Mario-Araya** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hii! My name is Mario Araya, I’m a Software Developer with 2+ years of experience. I have worked with backend technologies such as Cairo, Java, and C#, as well as frontend development using React, NextJS, and JavaScript/TypeScript. I’ve made contributions to open-source projects, completed a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings, and participated in multiple hackathons. I’m also a member of the Dojo Coding community here in Costa Rica.

### How I plan on tackling this issue
I will  create a new constant in the appropriate file with a minimum goal value of 500. Then, locate the newFund method (used by the fund manager) and add an assertion that ensures the input goal is greater than or equal to this new constant. Afterward, either modify existing tests or add new ones to validate that the newFund method enforces the minimum goal requirement correctly. Finally, ensure all tests pass.

**Comment by JoE11-y** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I'm Joseph a blockchain developer with over four years in blockchain and backend development, I’ve worked across different ecosystems, handling everything from smart contract design to on-chain interactions and protocol integration. I focus on building secure, scalable, and reliable blockchain applications, managing both on-chain and off-chain infrastructure.

### How I plan on tackling this issue
Begin by studying the codebase to ensure design consistency, then proceed to work on the task.

1. Study current codebase design
2. Leverage all provided resources within the issue to get a better grasp of the task at hand.
3. Implement the task.
4. Add tests to make sure the changes are working and no adverse effects
5. And lastly optimize

**Comment by jsandinoDev** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I'm a full-stack developer with web3 experience member of Dojo Coding, specializing in smart contracts and decentralized applications. I've worked on projects using React, Solidity, Cairo, and blockchain tools. My skills in both front-end and back-end development allow me to build scalable and secure solutions for web3 ecosystems.

### How I plan on tackling this issue
1. Create a New Minimum Goal Constant
Open the contract file where the constants are defined.
Add a new constant for the minimum goal.
2. Add the new assert in the newFund method.
3. Modify the newFund Method
4. Update or Add Test Cases

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I am a blockchain developer with vast knowledge in languages as cairo, typescript, javascript, Html, Css , solidity, React etc. My background in smart contract development and testing will enable me to implement this functionality effectively and ensure its robustness within the existing system.

### How I plan on tackling this issue
To address the issue of creating a new minimum goal constant, I would first create a new constant in the appropriate Cairo file, setting its value to 500. Next, I would modify the `newFund` method to include an assertion that checks if the input goal meets or exceeds this new constant. This will ensure that any new fund created has a minimum goal that aligns with our requirements. After implementing these changes, I would update existing tests or add new tests to validate that the assertion functions correctly and that the overall functionality of the method works as intended. Finally, I would run all tests to ensure that they pass successfully, confirming the reliability of the updates made.

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
i have prior experience in cairo and want to work on this one

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I am a cairo dev. A new-comer here, willing and ready to contribute to contribute to solve the issue.

**Comment by SoarinSkySagar** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
GM @adrianvrj, I am Sagar Rana, a smart contract developer and full stack engineer. I have 3 years of experience building robust full stack applications and over a year of writing smart contracts. You can see my projects and contributions to some major repos on my GitHub profile. The tech stack I use mainly includes Solidity, Rust, JavaScript and Typescript. I am also contributing to the Starknet and Rust ecosystems and building on Cairo and Rust languages. I am interested in contributing to projects like this to learn more about these technologies and help make these projects better. Please assign me as I would be really glad to be a contributor in this project! :)

### How I plan on tackling this issue
 - I would create a new constant in `constants/funds/fund_constants.cairo` called `MINIMUM_GOAL: u256` with value `500`
 - Modify `newFund` function with a new `assert` method that makes sure that input goal is greater than or equal to `FundConstants::MINIMUM_GOAL`
 - Modify test function with more testcases to make sure the function fails only when input goal is less than minimum goal

**Comment by Gerson2102** [comment]
---

### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to this project and other Cairo projects like:

- `Raito`
- `kakarot-ssj`

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---
