### ISSUE TITLE
[test] Test event emit when fund contract receives donation

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#144]
### This issue will be part of ODHack9.0, please apply via Onlydust app
- See #138 for more context.
- Add a test to make sure the event is emitting correctly with all the values expected.
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue

### Acceptance Criteria
- Event is being emitted correctly.
- Tests pass successfully.

**Comment by CollinsC1O** [comment]
Hello I'm a front-end and a blockchain developer and will love to work on this please assign

**Comment by Lukman-01** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hello! My name is Lukman, and I am a passionate Smart Contract Developer with two years of experience in writing smart contracts. My hands-on experience spans various blockchain platforms, including Ethereum and Starknet. I’m eager to leverage my skills in developing efficient, secure, and innovative solutions in the blockchain space.

### How I plan on tackling this issue
To address this issue, I will first review the implementation of the event in question to understand its expected values and parameters. Following this, I will create a comprehensive unit test that ensures the event is emitted correctly with all the required values, aligning with the acceptance criteria, and subsequently verify that all tests pass successfully.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer i would love to work on this issue 
Pleasee kindly assign :)

### How I plan on tackling this issue
i would make sure it is working

**Comment by Oshioke-Salaki** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I am a cairo developer with alot of contributions in the starknet ecosystem. I belive i would be a perfect fit for this issue and i would love to show case my skills in this repo if given the chance.

### How I plan on tackling this issue
I would first of all go through the code base to understand how everything works. then identify all functions that implements a donation to the fund contract.

then i would create the event and attach it to such functions. then i would write test cases to make sure the event is fired off when all goes well.

**Comment by No-bodyq** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hi, I'm Asher and I'll be working on issue #144.

I estimate this will take less than 2 days to complete.

### How I plan on tackling this issue
I will go through the code to get accustomed with its functionality then write tests to assert that the correct event, as well as its expected values are properly emitted using the assert_emitted method when the fund contract receives a donation

**Comment by anonfedora** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hi, I'm Eleazar and I'm applying to issue #144.

I estimate this will take 6hours max to complete.


### How I plan on tackling this issue
This is how I would tackle this issue:

Review the implementation of the function and Event struct

Ensure that the needed attributes of the Event struct are in place

Ensure code builds successfully and tests are passed successfully

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I am a blockchain developer with vast knowledge in languages as cairo, typescript, javascript, Html, Css , solidity, React etc..Leveraging my experience in smart contract testing, I would ensure that the test covers all possible scenarios to confirm the event's correctness and would run the tests to ensure they pass successfully.

### How I plan on tackling this issue
To address the issue of ensuring the correct emission of an event as outlined in issue #138, I would start by reviewing the relevant context in that issue to understand the expected event structure and values. I would then write a comprehensive unit test targeting the function responsible for emitting the event. This test would verify that the event is emitted with all the necessary attributes and that the emitted values match the expected outcomes.

**Comment by saimeunt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I have contributed to several Cairo projects on OnlyDust and I've worked on very similar issues in the past such as https://github.com/ArkProjectNFTs/bridge/pull/236

### How I plan on tackling this issue
I will carefully craft a test to make sure the event is emitted using Starknet Foundry and assert_emitted.

**Comment by 0xprivateChaos** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I bring 2 years of hands-on experience in writing and optimizing tests for Solidity smart contracts, which has given me strong foundation in blockchain testing patterns. Recently, I've expanded my expertise into Cairo development, actively writing contracts and their corresponding tests. My combination of established testing experience in Solidity and fresh perspective in Cairo, along with deep theoretical knowledge, positions me well to tackle this testing challenge effectively.

### How I plan on tackling this issue
Setup: Add event structure to Fund contract

Test Creation: Write a focused test function with user donating a contract 

Validation: Verify that event is emitted with correct details

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I am a cairo dev. A new-comer here, willing and ready to contribute to contribute to solve the issue

**Comment by BrunoAmbricca** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hello guys, I have been working for the past 4 years as a developer with multiple languages such as ts, and for the past 3 months learning and working with cairo on my own projects.

### How I plan on tackling this issue
I would look the method that needs to emit an event, follow the contributor guidelines, do the feature and test all it´s cases.

**Comment by mimiprosper** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Am a smart contract developer (solidity & starknet cairo). Am also a smart contract auditor and technical writer. As a smart contract auditor, testing is what i know in-depth and understand. I have audited lots of code bases. I understand how important thorough testing are in the web3 space. 

### How I plan on tackling this issue
I would follow the guideline in the repo for fork, clone & pull request. I would clone the project on my local machine. I would study the code base 
(fund contract receives donation events). Reading the code base will make me understand what events are expected to be emitted. Then i write test to make sure that what the fund contract receives donation events are expected to emit are correctly emitted.

**Comment by salazarsebas** [comment]
My background
As a member of the Dojo Coding community, I have experience in web2 and traditional technologies, as for web3 I have only been working for a few months and I have not yet managed to make my first contribution, however, it is not an impediment for me to do my best in this issue, I will devote the necessary effort to contribute to the OSS.

How I plan on tackling this issue
To solve this issue, I will perform the following steps:
- Understand in depth the context with issue 138 and also understanding in depth the contribution guide.
- Identify the values to be emitted and the event.
- Write the tests.
- Execute the test and verify that everythings works correctly.
- Deliver the prototype for the maintainers to give me feedback.

**Comment by blessingbytes** [comment]
Could I be assigned to this?

**Comment by GideonBature** [comment]
Hi, I'm Gideon Bature, a Software Engineer and I'll be working on issue #144.

I estimate this will take 2 days to complete.

This is how I would tackle this issue:

based on the issue #138 that emits an event when a fund contract receives a new donation in the receiveDonation method, I am going to do the following:

1. I will write a test using the spy events method and a mock up event to test and make sure that the event is emitting correctly all the expected values.
2. I will test using snforge from snfoundry to make sure the test passes successfully.

**Comment by obacollins-lab** [comment]
May I be assigned to this?

**Comment by Akshola00** [comment]
Is it okay if I take this?

**Comment by jaiminRaiyani** [comment]
I'd be happy to do this.

**Comment by SoarinSkySagar** [comment]
gm! I am Sagar Rana, and I am experienced in writing Cairo smart contracts along with snforge tests. you can check my contributions and my works on my github and onlydust profile. here is how I would approach this issue:
Once issue #137 is resolved, I will add the function test_receiveDonation in test_fund.cairo. I will add test cases to ensure that the function is working and the events are being emitted and will make sure the tests are passing before opening the PR.

**Comment by Pvsaint** [comment]
Mind if I take this issue?

**Comment by EmmanuelAR** [comment]
Hello @salazarsebas  this ticket is ready to work! Any questions let us know :)
