### ISSUE TITLE
[test] Test event emit when deploying a fund contract

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#147]
### This issue will be part of ODHack9.0, please apply via Onlydust app
- See #136 for more context.
- Add a test to make sure the event is emitting correctly with all the values expected.
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue

### Acceptance Criteria
- Event is being emitted correctly.
- Tests pass successfully.

**Comment by ooochoche** [comment]
@adrianvrj I have read the description and would love to work on this issue

**Comment by CollinsC1O** [comment]
Hello @adrianvrj I'm a frontend and a blockchain developer. I will love to work on this issue

**Comment by DiegoB1911** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I'm a Full Stack Developer with two years of experience. I'm also a member of Dojo Coding, where I'm expanding my expertise in Cairo and Web3 technologies. I'm enthusiastic about learning, and becoming a part of this project.

### How I plan on tackling this issue
To solve this, I will:
1. Analyze the contract functionality.
3. Develop a tests to verify that the event is emitted correctly using `assert_emitted`.
4. Verify that everything works as expected and document the code.

**Comment by Lukman-01** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hello! My name is Lukman, and I am a passionate Smart Contract Developer with two years of experience in writing smart contracts. My hands-on experience spans various blockchain platforms, including Ethereum and Starknet. I’m eager to leverage my skills in developing efficient, secure, and innovative solutions in the blockchain space.

### How I plan on tackling this issue
To tackle this issue, I will start by reviewing the relevant code and the specific event that needs testing, as outlined in #136. I will then implement a unit test that verifies the event is emitted with all expected values, ensuring that it adheres to the specified acceptance criteria, and finally, I will run the tests to confirm that they pass successfully.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer i would love to work on this issue 
Pleasee kindly assign :)

### How I plan on tackling this issue
i would make sure it is working

**Comment by jsandinoDev** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I'm a full-stack developer with web3 experience, specializing in smart contracts and decentralized applications. I've worked on projects using React, Solidity, Cairo, and blockchain tools. My skills in both front-end and back-end development allow me to build scalable and secure solutions for web3 ecosystems.

### How I plan on tackling this issue
o approach testing event emission during the deployment of a fund contract, follow these steps:

1. Understand the Event You Want to Test
When deploying smart contracts, certain actions or milestones should trigger events. For example, in your fund contract, you might have an event called FundCreated that signals successful contract deployment. You want to ensure this event is emitted correctly during deployment.
2. Set Up Testing Framework
3. Structure the Test
Now, you want to structure the test to capture and verify that the event is triggered as expected. This involves the following:

Deploy the Contract: You simulate the contract deployment process in your test environment.
Verify the Event: After deployment, check that the FundCreated event is triggered with the correct parameters (e.g., contract owner and amount).
4. Run the Test
After writing the test, you can run it in your development environment:

**Comment by Gianfranco99** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I have been a developer for over 4 years and have been contributing to the Starknet ecosystem for more than a year. My recent contributions include work on cairo-lint and scaffold-starknet. I’m eager to participate in this project as I see a lot of potential in it and believe it adds valuable functionality to the Starknet ecosystem. Also I'm part of dojo-coding comunity!

### How I plan on tackling this issue
I already commented to make the [issue ](https://github.com/web3wagers/gostarkme/issues/136) in which the event must be emitted, I would also like to make this issue since they are related, the ideal would be for the same person to do it so as not to have conflicts and not affect the development of the project.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I am a blockchain developer with vast knowledge in languages as cairo, typescript, javascript, Html, Css , solidity, React etc..I would utilize my experience in smart contract testing to ensure that the tests are comprehensive and pass successfully, confirming the correct behavior of the event emission functionality.

### How I plan on tackling this issue
To address the issue of testing the event emission, I would first review issue #136 for context and understand the specifics of the event and its expected values. I would then create a unit test that verifies whether the event is emitted correctly in the relevant function. This test will check that all expected values (e.g., donor address, donation amount, current balance, fund contract address) are present and accurate in the emitted event.

**Comment by saimeunt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I have contributed to several Cairo projects on OnlyDust and I've worked on very similar issues in the past such as https://github.com/ArkProjectNFTs/bridge/pull/236

### How I plan on tackling this issue
I will carefully craft a test to make sure the event is emitted using Starknet Foundry and assert_emitted.

**Comment by 0xprivateChaos** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I bring 2 years of hands-on experience in writing and optimizing tests for Solidity smart contracts, which has given me strong foundation in blockchain testing patterns. Recently, I've expanded my expertise into Cairo development, actively writing contracts and their corresponding tests. My combination of established testing experience in Solidity and fresh perspective in Cairo, along with deep theoretical knowledge, positions me well to tackle this testing challenge effectively.

### How I plan on tackling this issue
Setup: Add event structure to Fund contract and modify constructor to emit event upon deployment

Test Creation: Write a focused test function that deploys the contract and captures the deployment event

Validation: Assert that the emitted event contains correct fund details (id, owner, name, goal) matching the constructor parameters

**Comment by Emmanex01** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I'm Emmanuel Tochukwu, smart contract developer. I recently graduated from starknet developer bootcamp which lasted for 8 weeks. During the bootcamp, I have written a lot of contract. An also testing whether contract behaves as expected is one the things  I did.

### How I plan on tackling this issue
First, I would look at event struct to look at the variables to be emitted, and also check whether the annotations and importations are made.

secondly, I would write unit for every function that emits event using a spy_event() cheatcode which will allow me to be able to assert whether the right is emitted.

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I am a python dev. A new-comer here, willing and ready to contribute to contribute to solve the issue.

**Comment by dimka90** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I am a backend engineer with half a decade years of experience in creating and developing applications and smart contract that solves real life problems

### How I plan on tackling this issue
I will first of all go through the code to get an understanding of what the code those, then use test driven development method to write tests cases that solves ensure the events arie being emitted correctly.

**Comment by LazarusAA** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hi, I'm Alvaro Lazarus a blockchain developer and a new member of Dojo Coding, I've worked with testing Cairo contracts in the past which makes me confident I can complete this issue. Also it seem like a fun first contribution to the GoStarkMe project. 

### How I plan on tackling this issue
- Write unit tests to verify that the FundContractDeployed event is emitted with the correct values once the contract is set up.
- Run the tests using the testing framework to confirm they pass.

Thank you for your consideration

**Comment by mimiprosper** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Am a smart contract developer (solidity & starknet cairo). Am also a smart contract auditor and technical writer. As a smart contract auditor, testing is what i know in-depth and understand. I have audited lots of code bases. I understand how important thorough testing are in the web3 space. 

### How I plan on tackling this issue
I would follow the guideline in the repo for fork, clone & pull request. I would clone the project on my local machine. I would study the code base (deploying a fund contract events). Reading the code base will make me understand what events are expected to be emitted. Then i write test to make sure that what the deploying a fund contract events are expected to emit are correctly emitted.

**Comment by GideonBature** [comment]
Hi, I'm Gideon Bature, a Software Engineer and I'll be working on issue #147.

I estimate this will take 2 days to complete.

This is how I would tackle this issue:
1. Once issue #136 have been worked on, I will write a test using the spy events method to make sure it is emitting correctly all the expected values.
2. I will test using snforge from snfoundry to make sure the test passes successfully.

**Comment by blessingbytes** [comment]
I’d like to work on this.

**Comment by obacollins-lab** [comment]
Can I work on this, please?

**Comment by Eka1210** [comment]
My background and how it can be leveraged:

I'm currently a Computer Science student with a strong foundation in software development and a growing passion for blockchain technology. While this will be my first project in web3, I’m eager to apply my problem-solving skills and quickly learn the required tools. 

How I plan on tackling this issue:
1. I will start by reviewing the existing fund manager contract to understand how contracts are deployed and where the event needs to be emitted.
2. I will add the necessary logic to emit the event when the fund contract is successfully deployed. The event will contain the owner address, the new contract address, and the ID.
3.I will write tests to ensure that the event is emitted correctly with all the expected values, using a framework like Hardhat or Truffle.
4. I’ll run the tests to ensure the event is being emitted as expected and that no existing functionality is broken.
5. Finally, I will create a pull request and provide a detailed explanation of the changes, including use cases for the newly added event.

**Comment by Akshola00** [comment]
I'd be happy to do this.

**Comment by jaiminRaiyani** [comment]
Would love to tackle this!

**Comment by sasasamaes** [comment]
May I take this issue on?

ETA: 2 days

First review issue #147 and analyze the code and how it works
Create a test to emit when deploying a fund contract
Document the process

**Comment by shubha-me** [comment]
Could I take a shot at this?

**Comment by SoarinSkySagar** [comment]
gm! I am Sagar Rana, and I am experienced in writing Cairo smart contracts along with snforge tests. you can check my contributions and my works on my github and onlydust profile. here is how I would approach this issue:
Once issue #136 is resolved, I will add the function test_emitDeployment in test_fund.cairo. I would mock-deploy the contract in snforge using the declare and deploy mehtods and then check for emits. I will add test cases to ensure that the function is working and will make sure the tests are passing before opening the PR.

**Comment by Pvsaint** [comment]
I’d like to work on this.

**Comment by EmmanuelAR** [comment]
Hello @sasasamaes this ticket is ready to work! Any questions let us know :)
