### ISSUE TITLE
Add contributors guide

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#18]
We need to implement a contributors guide for new contributors, if you are willing to take this please contact me via Telegram to discuss it.

**Comment by JoshdfG** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
A full stack blockchain developer, My skills can be a little useful here as this deals with attention to details, tho requires little or no skill at all.

### How I plan on tackling this issue
well, I'd like to know your contributors guide and basically format in a readable and appealing way so everyone that reads it  can grasp what is being said.

**Comment by adrianvrj** [comment]
Hi @JoshdfG unfortunately we do not have enough resources to pay our contributors yet, would you still like to participate in this?

**Comment by JoshdfG** [comment]
No problem. I’ll work on it

**Comment by adrianvrj** [comment]
@JoshdfG assigned! feel free to contact me via telegram to talk about this
