### ISSUE TITLE
[fix] Remove unused UI's imports

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#181]
There are some unused imports all over the frontend application, please remove them.

**Comment by diegoTech14** [comment]
Hello @adrianvrj

I'm a software engineer from Costa Rica and a proud member of Dojo Coding. I've contributed to projects like ByteBeasts, Coffiblocks, and DipDup, and I have experience with technologies such as Cairo, JavaScript, React and others. I would love to contribute to this issue.

For this issue I will:
1. Check all files to find ever unused imports
2. Remove unused imports
3. Document if it's needed

Kind regards,
Diego Duarte Fernández

**Comment by sasasamaes** [comment]
Mind if I try this one?
-Search the entire app for unused imports

**Comment by SoarinSkySagar** [comment]
Would love to tackle this! I would check each and every file on the frontend for any unused imports and remove the ones that are not being used. I'll check that nothing breaks after I'm done working. Very straightforward task, would love to work on this.

**Comment by SudiptaPaul-31** [comment]
I'd like to work on this issue. I have experience in frontend cleanup and code optimization, so I’m confident I can handle this. Please assign me the issue if this approach works.
 Here is my approach to resolve this issue: 

I will scan each UI component for unused imports and will carefully remove the unused imports to ensure the code remains unaffected.

After removal, I will run existing tests to verify that everything works as expected and add any necessary tests.

**Comment by ManuelJG1999** [comment]
I’d like to work on this.

**Comment by adrianvrj** [comment]
@ManuelJG1999 assigned, feel free to reach us for any doubt/suggestion

**Comment by ManuelJG1999** [comment]
@adrianvrj thank you so much.
