### ISSUE TITLE
[feat] Donate functionality

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#183]
**Is your feature request related to a problem? Please describe.**
Currently we are letting people vote, once the vote goal is reached, users must be able to donate to the funding.

**Describe the solution you'd like**
If the funding state === 3, then the user should be able to donate to the contract and the contract balance should go up as user specified.

**Comment by Iwueseiter** [comment]
Hi @adrianvrj  can I quickly implement this?

**Comment by 0xdevcollins** [comment]
May I pick this up?

**Comment by DanielEmmanuel1** [comment]
Can i be assigned this?
