### ISSUE TITLE
[feat] Loading animation component

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#185]
**Is your feature request related to a problem? Please describe.**
Currently the app is taking some time to retrieve the data from the blockchain but this is not very clear on the UI, we need a loading animation for when this happens

**Describe the solution you'd like**
A simple loading animation component, without any text and with a light grey color. **Do not implement this component anywhere just add the necessary code.**

**Comment by sajalbnl** [comment]
May I take care of this?

**Comment by Snehagupta1907** [comment]
I'd be happy to do this.

**Comment by KevinLatino** [comment]
To solve the loading delay issue, I’d either create a custom spinner with a light grey color using CSS or Tailwind for simplicity and flexibility, or use a library like Chakra UI to leverage its pre-built loading components. Both approaches would improve the user experience by clearly indicating data loading without overwhelming the UI.

Here is an example of a loading spinner that i made in another project: 

const LoadingSpinner = () => {
  return (
    <div className="flex justify-center items-center h-full">
      <div className="w-12 h-12 border-4 border-gray-300 border-t-transparent rounded-full animate-spin"></div>
    </div>
  );
};

export default LoadingSpinner;

**Comment by sasasamaes** [comment]
I'd like to handle this task.
```
import React from 'react';
import './LoadingAnimation.css';

const LoadingAnimation = () => {
    return (
        <div className="loading-spinner"></div>
    );
};

export default LoadingAnimation;
```
```
.loading-spinner {
    width: 50px;
    height: 50px;
    border: 4px solid lightgrey;
    border-top: 4px solid transparent;
    border-radius: 50%;
    animation: spin 1s linear infinite;
}

@keyframes spin {
    0% {
        transform: rotate(0deg);
    }
    100% {
        transform: rotate(360deg);
    }
}```

**Comment by DiegoB1911** [comment]
I'm a Full Stack Developer with two years of experience, primarily in Next.js, and I'm also a member of Dojo Coding.

To address the issue I would:

1. Identify the Loading State: Add a loading state (isLoading) in the relevant part of the code where the app fetches blockchain data. Set this state to true when the request begins and false once the data is received.

2. Trigger the Animation: Use the isLoading state to conditionally display a loading animation in the UI whenever data is being retrieved.

3. Add the Loading Animation Code: Implement the plain code for a simple loading animation, without creating a separate component, for a lightweight solution.

4. Test and Document: Verify the functionality to ensure smooth transitions and document the code for clarity and future reference.

**Comment by Benjtalkshow** [comment]
I can take care of this issue My ETA is 24hrs

**Comment by martinvibes** [comment]
I’d like to work on this.
please kindly assign :)

**Comment by Kaminar-i** [comment]
I'd like to take this issue.
i'm an experienced developer and i would love to work on this issue

**Comment by Yunusabdul38** [comment]
i can help to work on a perfect animation/loading state for this issue, can I work on this issue!

**Comment by godspowerufot** [comment]
May I handle this issue? i am always keen to develop beautiful loading animation applying the skeleton approach where user are expecting an information to be render on a screen .Making it simple and unique is the best approach and i hope to be call upon to be able to contribute to this . thank you

**Comment by Michaelkingsdev** [comment]
Would like to work on this issue. it would be my first time contributing to this project. Thanks

**Comment by adrianvrj** [comment]
@KevinLatino assigned! feel free to implement the solution you consider the best, just take in account the component should match the looks of the app

**Comment by KevinLatino** [comment]
> @KevinLatino assigned! feel free to implement the solution you consider the best, just take in account the component should match the looks of the app

got it! I'll send you a message via Telegram with the result and you can check how it looks!
