### ISSUE TITLE
[fix] Delete dashboard heading

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#186]
**Is your feature request related to a problem? Please describe.**
Currently we are displaying a "Latest Funds" header in the dashboard page which does not look good.

**Describe the solution you'd like**
Delete the header and add margin to the fund cards section so they do not get up with the navigation bar.

**Comment by BrunoAmbricca** [comment]
Hello Adrian. I would like to contribute to this project by doing this issue.

**Comment by sajalbnl** [comment]
May I handle this issue?

**Comment by Mystic-Nayy** [comment]
Can I handle this task?

**Comment by Otaiki1** [comment]
May I be assigned to this?

**Comment by ShantelPeters** [comment]
Can i please be assigned to this issue @adrianvrj

**Comment by Benjtalkshow** [comment]
May I take this issue on? My ETA is 5hrs max.

**Comment by NueloSE** [comment]
May I try my hand at this?

**Comment by sasasamaes** [comment]
May I pick this up?
Remove the “Latest Funds” header: Locate the HTML element where the “Latest Funds” text is displayed in your code and delete it, so it no longer appears on the page.
	2.	Add margin to the fund cards section: To prevent the cards from overlapping with the navigation bar, add a margin to the card container.
```
.fund-cards-container {
    margin-top: 20px; /* Adjust the margin value as needed */
}
```
Make sure the margin is enough to keep the necessary distance from the navigation bar.

With these changes, the header should disappear, and the cards will be properly positioned on the page without interfering with the navigation.
ETA: 1 Day

**Comment by Michaelkingsdev** [comment]
I’d like to work on this. I would carefully solve this issue. And make PR in the next 3hrs. Thanks.

**Comment by petersdt** [comment]
Can I take care of this issue?

**Comment by DiegoB1911** [comment]
I'm a Full Stack Developer with two years of experience, primarily in Next.js, and a member of Dojo Coding.

To address the issue I would:

1. Remove the Header: Locate and remove the "Latest Funds" header to clean up the UI.
2. Add Margin to Fund Cards: Adjust the layout by adding margin to the fund cards to ensure they’re comfortably separated from the navigation bar.
3. Verify that everything is looking correctly

**Comment by wheval** [comment]
Hello @adrianvrj,
I'm Wheval, a Frontend developer with experience building clean and responsive UIs with react and tailwindcss.

To solve this issue, I’d delete the "Latest funds" header in the dashboard page. Then, I would add the right amount of margins depending on the screen size to the fund cards section using tailwind classes to ensure they don't get up with the navbar.
Next, I would test it on various breakpoint to ensure it looks good.  


ETA is 1 hour.

**Comment by martinvibes** [comment]
Suggested Attention-Grabbing Summary:

"🚀 Quick UI Win: Let's remove the clutter! The 'Latest Funds' header on the dashboard isn’t adding value and makes the layout feel cramped. By removing it and adding a clean margin above the fund cards, we’ll instantly improve the page's visual flow and user experience. Assign me this quick fix, and I'll have it polished in no time!"

**Comment by Kaminar-i** [comment]
Is this issue still available?
"Time for a dashboard makeover! 🚀 Let’s toss the 'Latest Funds' header and boost those fund cards with some margin magic. A clean look will not only enhance usability but also keep our navigation sleek and seamless.

Please kindly assign :)

**Comment by deeseeker** [comment]
I'd love to give this a go. 

ETA: 2-3hrs
