### ISSUE TITLE
[feat] Disable vote btn when wallet not connected

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#197]
**Is your feature request related to a problem? Please describe.**
Currently we are letting the user use the vote btn even if he is not connected.

**Describe the solution you'd like**
Please disable the btn and display a message indicating the user to connect to his wallet if he wants to vote for a funding.

**Comment by sajalbnl** [comment]
Can I work on this, please?

**Comment by jaiminRaiyani** [comment]
Would love to tackle this!

**Comment by pheobeayo** [comment]
Is it okay if I tackle this?

**Comment by sasasamaes** [comment]
I am a Dojo Member
Can I try solving this issue?
	1.	Disable the Vote Button: Ensure the “Vote” button is disabled by default if the user is not connected to their wallet.
	2.	Display a Message: Add a message next to or beneath the button (or as a tooltip) that says, “Please connect your wallet to vote for a funding.” This message should only be visible when the button is disabled due to the wallet not being connected.
	3.	Wallet Connection Check: Implement a check that verifies the wallet connection status before enabling the button. You can trigger this check when the page loads and each time the user interacts with the page to ensure they stay connected.
ETA: 3h

**Comment by godspowerufot** [comment]
Is it okay if I tackle this?
I am always keen to details and how I could approach a problem .I would try doing this 
Use a state check to monitor the wallet connection status.
Update the vote button’s behavior and display a tooltip or modal message when it’s disabled.
This feature will enhance the user experience by preventing attempts to vote without a connected wallet and providing clear feedback.

**Comment by KevinLatino** [comment]
Hello [adrianvrj](https://github.com/adrianvrj),

I am Kevin Latino,

I am a Frontend Dev and I Dojo Coding Member ⛩️

I will complete this issue in 2 hours.


For this issue I would first check if the `wallet` is connected by verifying if `wallet` has a value. Then, I would conditionally disable the "Vote" button based on this check. If the wallet isn’t connected, I’d disable the button and add a small message below it, prompting the user to connect their wallet to vote. This ensures that users can only vote if they are logged in, improving the user experience by preventing invalid interactions.

**Comment by adrianvrj** [comment]
@josephpdf assigned, feel free to reach us if any doubt!
