### ISSUE TITLE
[feat] Implement confirmation pages

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#199]
**Is your feature request related to a problem? Please describe.**
Currently when a funding is created/is voted/donated, we do not tell the user anything.

**Describe the solution you'd like**
Create a new page with its component to inform the user his action was completed.

**Comment by Iwueseiter** [comment]
Can I work on this?
I’m a frontend and smart contract developer.
I’d love to implement this feature.
ETA: 24hrs
