### ISSUE TITLE
[test] ⁠Add test_emit_event_donation_withdraw test

### ISSUE THREAD

**Issue by EmmanuelAR** [web3wagers/gostarkme#211]
### This issue will be part of ODHack 10.0, please apply via Onlydust app
- [ ] Add test_emit_event_donation_withdraw test for withdraw method in contracts/src/fund.cairo
- [ ] Validate that the event should be emitted when the withdraw method occurs 

**Notes (PLEASE READ)**

1. Withdraw method was already test but we remove receive_donation method so we have to refresh the withdraw test.
2. In contracts/tests/test_fund.cairo file there are the past wothdraw methods commented, I leave it there so you can take reference.
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue.

**Comment by Mystic-Nayy** [comment]
I'd like to take this issue.

**Comment by Benjtalkshow** [comment]
Let me try this one!

**Comment by NueloSE** [comment]
Is it okay if I tackle this?

**Comment by petersdt** [comment]
I can work on this ETA <= 24hrs

**Comment by casweeney** [comment]
I am an experienced Cairo developer who has written and tested complex Cairo smart contracts.

I can handle this task.

## ETA: 6 hours

**Comment by anihdev** [comment]
May I take this issue on?
i have good knowledge of cairo and can deliver a very advanced test suite for this

**Comment by No-bodyq** [comment]
Could I try solving this?

**Comment by mayasimi** [comment]
I can handle this task kindly assign me ETA <=24hrs

**Comment by DADADAVE80** [comment]
Could I grab this task?

**Comment by martinvibes** [comment]
hey @EmmanuelAR i'm a blockchain dev and I'd like to take this issue.
kindly assign :)

**Comment by Michaelkingsdev** [comment]
@EmmanuelAR 
Please permit me to take care of this. 48hrs max

**Comment by dev-chinx** [comment]
holla @EmmanuelAR mind if i take on this issue :)
i would love to be a contributor on your project

**Comment by wheval** [comment]
Hello @emmanuelar ,

I'm Wheval. A frontend dev and cairo developer.
I would ensure to add the test with reference to the current contract code.
I would also ensure that tests passes and emits the event.

Thank you. 
ETA is 2days.

**Comment by Kaminar-i** [comment]
I'd love to give this a go @EmmanuelAR mind if i take on this issue :)

**Comment by ShantelPeters** [comment]
Please can I be assigned to this issue @EmmanuelAR

**Comment by derianrddev** [comment]
Hi, I'm Derian, I'm a software engineer focused on fullstack web development and I'm currently part of Dojo Coding. I have been studying Cairo through the Starknet Bootcamp, completed all the Starklings exercises and have been practicing on Node Guardians. I would like to work on this topic and gain more experience.

I estimate that it will take me a day to complete. 

Here is how I would approach this issue:
- Uncomment the test_emit_event_donation_withdraw method in the contracts/tests/test_fund.cairo file.
- Adjust the decommented test, remove any reference to receive_donation.
- Run the tests to verify that withdraw works correctly.

**Comment by sasasamaes** [comment]
Can I be assigned to this?
1.	Understand the withdraw event logic:
Since the withdraw method should emit an event, check the contracts/src/fund.cairo file to confirm the expected event. Typically, the event may include information like the sender, the amount withdrawn, or any related transaction ID.
	2.	Review the previous withdraw tests:
As the previous withdraw methods are commented out in test_fund.cairo, use these as a reference for structuring the new test, making sure it aligns with the current setup that no longer includes the receive_donation method.
	3.	Set up the test_emit_event_donation_withdraw:
	•	Initialize the necessary variables, such as balances, contract instances, or accounts.
	•	Call the withdraw method.
	•	Verify that the expected event was emitted by asserting the event details, such as the withdrawn value and any other relevant parameters.
	4.	Validate the emitted event:
Use specific assertion functions to ensure the event data matches the expected values. If the testing framework for Cairo includes functionality to check emitted events, utilize this to confirm the event is correctly triggered upon withdraw.
ETA: 1 Day

**Comment by EmmanuelAR** [comment]
hey @Mystic-Nayy any update? 😄

**Comment by dev-chinx** [comment]
hey @EmmanuelAR i can help fix this isssue if the person assigned hasn't fixed it yet
Thanks!

**Comment by EmmanuelAR** [comment]
Hey @Mystic-Nayy could you please given an update?

**Comment by casweeney** [comment]
@all-contributors please add @casweeney for code.

**Comment by lauchaves** [comment]
Hey @EmmanuelAR! I'm Lau Chaves from Dojo Coding Costa Rica. I noticed this has been open for a while. I’d love to work on this! I’ll use the commented tests in test_fund.cairo as a reference. Let me know if I can take it on.

**Comment by casweeney** [comment]
@EmmanuelAR Can I take this up? I know how the codebase work. I can quickly tackle this issue.

## ETA: 4 - 5 hours.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by mimisavage** [comment]
Is it okay if I take this?

**Comment by OWK50GA** [comment]
Hi, I'm Wilfrid, a Cairo Smart Contract Developer adept at writing tests, and I'll be working on issue #[Issue Number].

I estimate this will take 1 Day to complete.

This is how I would tackle this issue:
I will use the starknet::pop_log function for this test, combined with the Option for streamlining the messages I want depending on what is returned

**Comment by GideonBature** [comment]
Can I take care of this issue?

My name is Gideon Bature, a Software Engineer with experience building Starknet based smart contracts, using Cairo. If given this issue, I should be able to send my first PR within 48 hrs. 

Thank you!

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo and rust projects like chaineventt etc  .   please /assign  this issue .
Thank You

**Comment by ikezuby2012** [comment]
hello, can i be assigned this issue?

my name is nnubia nzube, i'm a software developer with experience in writing smart contract using cairo, my ETA is within 48 hours.

**Comment by Emmanex01** [comment]
Can I be assigned to this?
I'm Emmanuel Tochukwu, software developer. I have experience writing and testing smart contract on Starknet. I would love to work on this.

**Comment by saimeunt** [comment]
Hey I'm a returning contributor and already worked on this specific part of the codebase. I think it will take 1 day to complete.

**Comment by lauchaves** [comment]
@EmmanuelAR this one is ready for review 🚀
