### ISSUE TITLE
 [fix] Footer links

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#247]
### This issue will be part of ODHack10, please apply via Onlydust app
-  Fix the footer links in order to send the user to a blank page instead of opening the links on the same tab.
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue.

**Comment by NueloSE** [comment]
@adrianvrj 
Hi, I'm nuelo and I'll be working on issue #247.

I estimate this will take 12hr to complete.

This is how I would tackle this issue:

**Comment by MariangelaNM** [comment]
Hi, I'm Mariángela, and I'll be working on issue #247.

Here's my approach to tackle this issue:

-  Add target="_blank" to the relevant links.

- Update dynamically rendered links to ensure proper behavior.

- Test thoroughly to verify functionality and usability improvements.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by abdegenius** [comment]
I'd love to work on this!

**Comment by wheval** [comment]
Hello @adrianvrj, I'm Wheval a  frontend developer with multiple experiences working with Nextjs and TypeScript. Can i work on this?

I would ensure the user opens a blank page when they click. This can be easily done with a _blank target attribute.
I would also test it on my devices.

ETA is 5 hours.

**Comment by Kingsuite** [comment]
I'd like to handle this task.

**Comment by OWK50GA** [comment]
Hi, I'm Wilfrid, a Frontend Web Developer and I'll be working on issue #247

I estimate this will take 3 hours to complete.

This is how I would tackle this issue:
I will trace where the links are gotten in the footer component, and update their hrefs to send the user to a blank page

**Comment by lauchaves** [comment]
Hi, I'm Lau Chaves and I'll be working on issue #247

I estimate this will take less than 10h to complete.

This is how I would tackle this issue:
I update the <a> tags in the footer component to include the target="_blank" and rel="noopener noreferrer" attributes.

I have over 5 years of experience working with JavaScript, React, and TypeScript, ruby... Im also part of Dojo Coding Costa Rica!

**Comment by Benjtalkshow** [comment]
Could I take a shot at this?

**Comment by GideonBature** [comment]
May I take this issue on?

My name is Gideon Bature, a Software Engineer with experience using TypeScript. If assigned, I should be able to send my first PR within 48 hrs. 

Thank you!

**Comment by Bran18** [comment]
Hello there. I’m Brandon, part of the ⛩️ Dojo Coding community, and I would love to contribute to this project! 🚀  This might be my first contribution here.

I've done quite a few of these ones in our DEFI/Web3 apps, I'm part of the Bitcash/Bitlauncher team https://bitlauncher.ai/en  (this is a really similar app to the one you have). And I would love to help out with the fix of the links. 

Lmk if I can start working on it.  Here’s my GitHub profile: GitHub: https://github.com/Bran18 and my OnlyDust profile: https://app.onlydust.com/u/Bran18. 

BTW tks for taking the time 🙏

**Comment by ShantelPeters** [comment]
I’m interested in this one.

**Comment by Michaelkingsdev** [comment]
Can I be assigned to this?  I am an experienced frontend developer with 3 years of experience.

**Comment by bydan0** [comment]
I’d like to resolve this. I will add a "target _blank" to open in new tab the links properly because they are external links :)

**Comment by Jimmy-csc** [comment]
Hi, I’m interested in this issue.

**Comment by MullerTheScientist** [comment]
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript. please i'd love to jump on this task

**Comment by mariocodecr** [comment]
Hii! My name is Mario Araya, I’m a Software Developer with 2+ years of experience. I have worked with backend technologies such as Cairo, Java, and C#, as well as frontend development using React, NextJS, and JavaScript/TypeScript. I’ve made contributions to open-source projects, completed a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings, and participated in multiple hackathons. I’m also a member of the Dojo Coding community here in Costa Rica.

I will modify the footer links to ensure they open in a new tab instead of the same tab. This can be achieved by adding the target="_blank" attribute to the anchor (<a>) tags in the footer. Additionally, I will ensure that the rel="noopener noreferrer" attribute is included for security reasons, to prevent any potential vulnerabilities from opening the link in a new tab.

**Comment by ryzen-xp** [comment]
Could I take over this issue?

**Comment by Amarjeet325** [comment]
I’d like to help with this.

**Comment by Supa-mega** [comment]
Could I try solving this?

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend developer with experience
i would really love to contribute to your project 
kindly assign :)

**Comment by akintola4** [comment]
Can I take care of this issue?i would love to build it , this is my  twitter account for my works https://x.com/photofola , i would be happy if i am give this task for my first ever task on this platform
