### ISSUE TITLE
[feat] Disable vote btn

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#248]
### This issue will be part of ODHack10, please apply via Onlydust app
- If the user already voted to the funding, disable the vote btn for him.
- There is a getVoter function in the backend, you can use that function to achieve this.
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue.

**Comment by martinvibes** [comment]
Hi, I'm martin and I'll be working on issue #248.

I estimate this will take 48hrs to complete.

This is how I would tackle this issue:
- Use getVoter Function: Fetch the user's voting status from the backend.
- Update Frontend: Add logic to check if the user has already voted.
- Disable Button: If the user has voted, set the button as disabled (disabled attribute).
- Style Button: Adjust the disabled button's appearance (e.g., gray it out).
- Test Functionality: Ensure correct behavior for both voted and non-voted users.

i would love to work on this issue kindly assign :)

**Comment by raizo07** [comment]
Could I be assigned to this? I'm a software developer with over four years of experience

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by abdegenius** [comment]
Could I take over this issue?

**Comment by ncoquelet** [comment]
I’d love to work on this task.

# Presentation

Hello, I'm senior developer, comfortable with Typescript, React/Vite/Next, testing, CI/CD, docs and I'm a beginner on Cairo (starklings 100% and NodeGuardians “Entering Cairo”, “Thinking in Cairo”, “Vanity Address”, and I continue).
I'm rigorous and diligent, I'm used to contributing my skills to projects and can move really quickly.

# How do I resolve this issue?

I will Implement specifications.

- disable voting button, if user already voted 
- using getVoter function as mentioned 

Contributors guide checked !

**Comment by Benjtalkshow** [comment]
Can I jump on this task?

**Comment by Bran18** [comment]
Hello there. I’m Brandon, part of the ⛩️ Dojo Coding community, and I would love to contribute to this project! 🚀  This might be my first contribution here.

I've done quite a few of these ones in our DEFI/Web3 apps, I'm part of the Bitcash/Bitlauncher team https://bitlauncher.ai/en  (this is a really similar app to the one you have). And I would love to help out with the creation of the guard validation. 

Lmk if I can start working on it.  Here’s my GitHub profile: GitHub: https://github.com/Bran18 and my OnlyDust profile: https://app.onlydust.com/u/Bran18. 

BTW tks for taking the time 🙏

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo and rust projects like chaineventt etc  .   please /assign  this issue .
Thank You

**Comment by ShantelPeters** [comment]
Can I take this from here?

**Comment by Villarley** [comment]
Hi, I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.

I’ll be working on issue #248

I estimate this will take 24-48 hours to complete.

This is how I would tackle this issue:

Use the getVoter function from the backend to determine if a user has already voted.
Disable the vote button for users who have already cast their vote.
Implement dynamic behavior so the button state updates based on the voting status.
Test the functionality across various scenarios to ensure it works seamlessly.
Ensure the implementation aligns with the contributors’ guide and project standards.

Pls feel free tor reach out!!!!

**Comment by Michaelkingsdev** [comment]
Can I be assigned to this?  I am an experienced frontend developer with 3 years of experience.

**Comment by MullerTheScientist** [comment]
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript. please i'd love to address this task.

**Comment by Amarjeet325** [comment]
Could I grab this task?

**Comment by Supa-mega** [comment]
Can I work on this, please?

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend developer with experience
i would really love to contribute to your project 
kindly assign :)

**Comment by adrianvrj** [comment]
@kimcascante any updates on this? :)

**Comment by kimcascante** [comment]
@adrianvrj creating PR right now :)
