### ISSUE TITLE
[feat] Display withdraw btn only for owner

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#249]
### This issue will be part of ODHack10, please apply via Onlydust app
- If the funding reached the STRk goal, display the withdraw btn only for the funding owner.
- Display the donation btn if the user is not the owner.
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by abdegenius** [comment]
I can comfortably handle this issues

**Comment by ncoquelet** [comment]
Let me handle this issue!

# Presentation

Hello, I'm senior developer, comfortable with Typescript, React/Vite/Next, testing, CI/CD, docs and I'm a beginner on Cairo (starklings 100% and NodeGuardians “Entering Cairo”, “Thinking in Cairo”, “Vanity Address”, and I continue).
I'm rigorous and diligent, I'm used to contributing my skills to projects and can move really quickly.

# How do I resolve this issue?

- display withdraw btn only if user is the funding owner
- display donation btn else

Contributors guide checked !

**Comment by OWK50GA** [comment]
Hi, I'm Wilfrid, a Frontend Web Developer and I'll be working on issue #249.

I estimate this will take 1 Day to complete.

This is how I would tackle this issue:
I will create a flow to get the address of the funding owner, and create a Boolean variable to check if it is equal to the current user wallet address.

Based on the Boolean, I will display the withdraw button.
I will also use tools like logs to the console to avoid petty oversight like removal/addition of '0x' to addresses that could happen

**Comment by Benjtalkshow** [comment]
I'd like to handle this task.
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 72hrs. Thanks

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo and rust projects like chaineventt etc  .   please /assign  this issue .
Thank You

**Comment by ShantelPeters** [comment]
Let me handle this issue!

**Comment by Michaelkingsdev** [comment]
Can I be assigned to this?  I am an experienced frontend developer with 3 years of experience.

**Comment by wheval** [comment]
Hello @adrianvrj, May I be assigned to this?

I have worked on something similar in the past.
Please assign. Thank you.

ETA is 1 day.

**Comment by Villarley** [comment]
Hi, I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.

I’ll be working on issue #249.

I estimate this will take 2-4 days to complete.

This is how I would tackle this issue:

Implement logic to check if the funding has reached the STRk goal.
Display the withdraw button for the funding owner when the goal is met.
Show the donation button for users who are not the funding owner.
Test the implementation thoroughly to ensure button states behave correctly based on user roles and funding status.
Follow the contributors’ guide to ensure the solution meets project standards.


Pls feel free to reach out!!!

**Comment by MullerTheScientist** [comment]
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript. please I would love to contribute to this task

**Comment by ikezuby2012** [comment]
hello, can i be assigned this issue?

my name is nnubia nzube, i'm a software developer with experience in both frontend and backend and also in writing smart contract using cairo, my ETA is within 2 - 4 days.

How i aim to handle this issue
1. an if check to check if strk funding has hits its goal.
2. only the owner can see the withdraw button.
3. normal users can see the donate button.
4. then write tests to test all conditions
