### ISSUE TITLE
[fix] Enable not connected users to see the dashboard 

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#250]
### This issue will be part of ODHack10, please apply via Onlydust app
- If a user is not connected the user should still be able to see the fundings in the dashboard.
- Apply the changes in order to display the fundings on the dashboard without being connected to the app.
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Supa-mega** [comment]
can i be assigned this project

**Comment by Iwueseiter** [comment]
I'm a frontend and smart contract developer. I have a solid background in tailwindCSS, react, nextjs, javascript, typescript, cairo, rust ETC.

**Comment by ncoquelet** [comment]
# Presentation

Hello, I'm senior developer, comfortable with Typescript, React/Vite/Next, testing, CI/CD, docs and I'm a beginner on Cairo (starklings 100% and NodeGuardians “Entering Cairo”, “Thinking in Cairo”, “Vanity Address”, and I continue).
I'm rigorous and diligent, I'm used to contributing my skills to projects and can move really quickly.

# How do I resolve this issue?

I will Implement specifications.

- display funding in the dashboard for all users (even if user is not connected)

Contributors guide checked !

**Comment by ShantelPeters** [comment]
I’d like to help with this.

**Comment by MrRoudyk** [comment]
Can I work on this, please?

**Comment by Michaelkingsdev** [comment]
Can I take care of this issue?

**Comment by brolag** [comment]
Hi, I'd like to work on this issue:

Here's how I'd fix it:

- Check any validations for a connected address in order to display the dashboard component.
- Add a provider that doesn't rely on a connected wallet.
- Adjust the dashboard component to show the funds.

Estimate: 2~3 h

Thanks!

**Comment by MullerTheScientist** [comment]
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript. i would love to contribute to this task

**Comment by FemiOje** [comment]
Hi, I'm a frontend developer with 3+ years experience. I am looking to contribute to Go Stark Me for the first time, after participating in the recently conducted testing, and I hope to work on issue #250.

I estimate this will take 12 hours to complete.

This is how I would tackle this issue:
1. Fork the repo and create a branch for the issue.
2. In frontend/gostarkme-web/app/app/page.tsx, remove the "wallet" variable from the conditions in lines 74-101
( {!wallet &&
        <div className="text-center text-gray-500 mt-32">
          Please connect your wallet to see funding dashboard.
        </div>
      }

      {loading && wallet && <div className="text-center text-gray-500 mt-12">
        <LoadingSpinner />
        <div className="text-center text-gray-500">
          Loading funds...
        </div>
      </div>}

      {funds.length !== 0 && !loading && wallet &&
        <div className="grid grid-cols-1 md:grid-cols-2 gap-x-4 gap-y-6 md:gap-x-[138px] md:gap-y-[84px] mt-10 lg:mt-12">
          {funds.map((fund: { type: string; title: string; description: string; fund_id: string }, index: number) => (
            <FundCards key={index} fund={fund} index={index} />
          ))}
        </div>
      }

      {funds.length === 0 && !loading && wallet &&
        <div className="flex justify-center items-center h-64">
          <div className="text-center text-gray-500">
            There is no fundings to display.
          </div>
        </div>
      })
3. Test extensively to ensure there are no bugs.
4. Submit pull request.

thank you
