### ISSUE TITLE
[feat]  Update donation display

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#251]
### This issue will be part of ODHack10, please apply via Onlydust app
- Update the donation display so that when the user donates, the progress bar and donation amount actually adds after user approved the tx.
- This will disable the redirecting to the confirmation page.
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by abdegenius** [comment]
May I pick this up?

**Comment by Kingsuite** [comment]
I’d like to work on this.

**Comment by ncoquelet** [comment]
I'd be happy to do this.

# Presentation

Hello, I'm senior developer, comfortable with Typescript, React/Vite/Next, testing, CI/CD, docs and I'm a beginner on Cairo (starklings 100% and NodeGuardians “Entering Cairo”, “Thinking in Cairo”, “Vanity Address”, and I continue).
I'm rigorous and diligent, I'm used to contributing my skills to projects and can move really quickly.

# How do I resolve this issue?

I will Implement specifications.

- display funding in the dashboard for all users (even if user is not connected)

Contributors guide checked !

**Comment by OWK50GA** [comment]
Hi, I'm Wilfrid and I'll be working on issue #251

I estimate this will take 2 Days to complete.

This is how I would tackle this issue:
I will check the current logic handling the updating of the donation carefully for what makes it break/not function when a donation is approved. 
I will then fix the logic to make sure it watches for transaction approval, and the amount is added after while also considering optimality of my logic. 
I will also check if there is another thing causing redirect to the confirmation page and fix it as well.

**Comment by Unickhub** [comment]
I’d like to resolve this. i will really appreciate it

**Comment by Benjtalkshow** [comment]
I'd like to handle this task.
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 48hrs. Thanks

**Comment by ShantelPeters** [comment]
Can I be assigned to this?

**Comment by wheval** [comment]
May I be assigned to this?

**Comment by josephpdf** [comment]
Hi! @adrianvrj
I'm Joseph Poveda, I'm a member of the Dojo Coding community.
A bit about my background is that I'm just starting out with Only Dust and I want to contribute as much as I can to the project. My knowledge of different programming languages ​​will allow me to better solve problems.
To solve this issue I will:
1. **Update the Donation Display Logic:**
- Modify the code to update the progress bar and donation amount immediately after the user approves the transaction.
2. **Disable Redirection:**
- Remove or disable the code that redirects the user to the confirmation page after the donation is made.
3. **Handle Transaction Approval:** 
- Ensure that the donation display updates only after the transaction is successfully approved.
4. **Test the Changes:** 
- Verify that the progress bar and donation amount update correctly without redirecting to the confirmation page.
- Ensure that the user experience remains smooth and intuitive.
5. **Follow Contribution Guidelines:**
- Apply via the Onlydust app as required for ODHack10.
- Read the contributors guide before starting the implementation.

**Comment by AnoukRImola** [comment]
Hi Guys! I haven’t worked with you yet. Could I take this issue? I don’t want to be redundant with the steps to resolve it since the description is quite clear about what needs to be done :)

**Comment by ryzen-xp** [comment]
I'd love to give this a go.

**Comment by ikezuby2012** [comment]
hello, can i be assigned this issue?

my name is nnubia nzube, i'm a software developer with experience in writing javascript/typescript and also smart contract using cairo, my ETA is within 24 hours.

**Comment by adrianvrj** [comment]
@AnoukRImola any updates on this? :)

**Comment by AnoukRImola** [comment]
> @AnoukRImola any updates on this? :)

I’m starting to work on it right now; I hope to submit the PR by tomorrow 🫡
