### ISSUE TITLE
[feat] Add new asserts to set_name

### ISSUE THREAD

**Issue by EmmanuelAR** [web3wagers/gostarkme#252]
### This issue will be part of ODHack10, please apply via Onlydust app
- Add new assert that validate that the caller should be the admins in set_name method in contracts/src/fund.cairo
- The admins are two (VALID_ADDRESS_1,VALID_ADDRESS_2) constants located in contracts/src/constants/funds/fund_manager_constants.cairo
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue.

**Comment by vestor-dev** [comment]
Hi, I'm martin and I'll be working on issue #252.

I estimate this will take 48hrs to complete.

This is how I would tackle this issue:

1. Locate set_name: Find the method in contracts/src/fund.cairo.
2. Access Admin Constants: Use VALID_ADDRESS_1 and VALID_ADDRESS_2 from fund_manager_constants.cairo.
3. Add Admin Check: Add an assert to verify the caller's address matches one of the admin constants.

it will be my first time on this repo

**Comment by GoSTEAN** [comment]
Can I work on issue #252
### Background 
I am a smart contract developer with hands-on experience in writing and deploying decentralized applications (dApps). I specialize in using Cairo, the programming language for StarkNet, to develop scalable and efficient smart contracts.
### Steps to solve it

1. Understand the Contributor's Guide

      Read the guide carefully to ensure compliance with project standards for contributions, coding style, and testing requirements.
2. Locate Relevant Files and Constants
Navigate to contracts/src/fund.cairo to find the set_name method.
Identify the constants VALID_ADDRESS_1 and VALID_ADDRESS_2 in contracts/src/constants/funds/fund_manager_constants.cairo.
3. Modify the set_name Method
Add an assert statement in the set_name method to check if the caller's address matches either VALID_ADDRESS_1 or VALID_ADDRESS_2.
Use Cairo’s syntax for assertions, ensuring it aligns with existing patterns in the codebase.
4. Write Tests for Validation
Implement test cases to verify that the set_name method only allows calls from the valid admin addresses.
Include negative tests to ensure unauthorized addresses are blocked.
5. Submit and Verify
Test the changes locally, ensuring compliance with the contributor's guide.

**Comment by Emmanex01** [comment]
Could I take over this issue?

**Comment by ncoquelet** [comment]
I'd like to take this issue.

# Presentation

Hello, I'm senior developer, comfortable with Typescript, React/Vite/Next, testing, CI/CD, docs and I'm a beginner on Cairo (starklings 100% and NodeGuardians “Entering Cairo”, “Thinking in Cairo”, “Vanity Address”, and I continue).
I'm rigorous and diligent, I'm used to contributing my skills to projects and can move really quickly.

# How do I resolve this issue?

I will Implement specifications.

- add new assert like specified
- after that I can tacle #256

Contributors guide checked !

**Comment by GideonBature** [comment]
I’d like to work on this.

My name is Gideon Bature, a Software Engineer with experience building Starknet based smart contracts, using Cairo. If given this issue, I should be able to send my first PR within 48 hrs. 

Thank you!

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo and rust projects like chaineventt etc  .   please /assign  this issue .
Thank You

**Comment by jsanchez556** [comment]
Hi, my name is José Mario from Costa Rica, a Full stack developer with more than 15 years in development and a focus in TypeScript, JavaScript, Nodejs and React. Open Source projects are something I enjoy, and I am now learning on Rust, and Cairo, I recently contribute to some Rust projects. About my learning and growth in the industry, I started doing ODHacks as early as version 7.0 due to my work with Dojo Coding. I am excited to utilize my wealth of experience and experience to new technologies to meet new challenges and deliver results.

How to tackle this feature:
Locate set_name function in contracts/src/fund.cairo and add a new validation  to ensure the caller is either VALID_ADDRESS_1 or VALID_ADDRESS_2, then add proper test to verify that set_name works for VALID_ADDRESS_1 or VALID_ADDRESS_2.

**Comment by petersdt** [comment]
Can I take this issue?

i am a frontend developer with experience in writing and testing smart contract kindly assign me this issue ETA <= 24hrs

**Comment by ShantelPeters** [comment]
May I try my hand at this?

**Comment by SoarinSkySagar** [comment]
May I work on this issue @EmmanuelAR?

I am an experienced cairo dev and a regular contributor at @keep-starknet-strange.

eta: 3 days

**Comment by Kom02** [comment]
Hi, My name is Kevin Obando, a full stack junior developer with 2 years of experience from Costa Rica. I am starting in this community and I want to help in this project.

**Comment by akintewe** [comment]
Hi, I'm akintewe and I'll be working on issue
I have experience in cairo and typescript 

I estimate this will take 24hrs to complete.

I would tackle this issue with these steps:

i will first locate set_name: Find the method in contracts/src/fund.cairo.
Access Admin Constants: Use VALID_ADDRESS_1 and VALID_ADDRESS_2 from fund_manager_constants.cairo.
I will also dd Admin Check: Add an assert to verify the caller's address matches one of the admin constants.
I am a new contributor, happy to help :)

**Comment by Supa-mega** [comment]
Can I be assigned to this?

**Comment by ikezuby2012** [comment]
hello, can i be assigned this issue?

my name is nnubia nzube, i'm a software developer with experience in writing smart contract using cairo, my ETA is within 24 hours.

**Comment by saimeunt** [comment]
Hey, I'm a returning contributor having previously worked on testing gostarkme, I think this can be completed in half a day.

**Comment by jsanchez556** [comment]
Hi, @EmmanuelAR:

Please check the PR: https://github.com/web3wagers/gostarkme/pull/260
