### ISSUE TITLE
[feat] Add new asserts to set_goal

### ISSUE THREAD

**Issue by EmmanuelAR** [web3wagers/gostarkme#254]
### This issue will be part of ODHack10, please apply via Onlydust app
- Remove assert where the fund manager can call the method.
- Add new assert that validate that the caller should be the admins in set_goal method in contracts/src/fund.cairo
- The admins are two (VALID_ADDRESS_1,VALID_ADDRESS_2) constants located in contracts/src/constants/funds/fund_manager_constants.cairo
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue.

**Comment by Kingsuite** [comment]
Hi, I'm  and I'll be working on issue #[Issue Number].

I estimate this will take 2hrs to complete.

This is how I would tackle this issue:
[Steps to solve issue]

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by josephchimebuka** [comment]
Could I try solving this?

**Comment by anihdev** [comment]
just concluded a cairo basecamp acquiring an nft of participation, im very confident i can handle this. ill be happy if i get assigned

**Comment by Gerson2102** [comment]
---

### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to other projects like:

- `kakarot-rpc`
- `ef-tests`
- `Raito`
- `Starknet-Phone`

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---

**Comment by ncoquelet** [comment]
Can I take this from here?

# Presentation

Hello, I'm senior developer, comfortable with Typescript, React/Vite/Next, testing, CI/CD, docs and I'm a beginner on Cairo (starklings 100% and NodeGuardians “Entering Cairo”, “Thinking in Cairo”, “Vanity Address”, and I continue).
I'm rigorous and diligent, I'm used to contributing my skills to projects and can move really quickly.

# How do I resolve this issue?

I will Implement specifications.

- add new assert like specified
- after that I can tacle #258

Contributors guide checked !

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo projects like chaineventt .   please /assign  this issue .
Thank You

**Comment by ShantelPeters** [comment]
May I try my hand at this?

**Comment by MrRoudyk** [comment]
May I pick this up?

**Comment by wheval** [comment]
I'd love to give this a go.

**Comment by casweeney** [comment]
## Tackling this issue:

I will create a test for the `set_goal()` function that will first set the gaol and then assert that the goal was properly set by calling the `get_goal()` and asserting that it returned the value that was set.

**Comment by SoarinSkySagar** [comment]
May I work on this issue @EmmanuelAR?

I am an experienced cairo dev and a regular contributor at @keep-starknet-strange.

eta: 3 days

**Comment by Kom02** [comment]
Hi, My name is Kevin Obando, a full stack junior developer with 2 years of experience from Costa Rica. I am starting in this community and I want to help in this project.

**Comment by akintewe** [comment]
Hi, I'm akintewe and I'll be working on issue
I have experience in cairo and typescript 

I My ETA is > 24hrs to complete.

I would tackle this issue with these steps:

i will first locate set_name: Find the method in contracts/src/fund.cairo.
Access Admin Constants: Use VALID_ADDRESS_1 and VALID_ADDRESS_2 from fund_manager_constants.cairo.
I will also dd Admin Check: Add an assert to verify the caller's address matches one of the admin constants.
I am a new contributor, happy to help :)

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend developer with experience
i would really love to contribute to your project 
kindly assign :)

**Comment by sotoJ24** [comment]
Hello team, greetings, I have knowledge in Cairo and performance tests, stress, bigO algorithm analysis, test speed, clean code, I think I can work on it,

Josué,
De Dojo Coding

**Comment by Emmanex01** [comment]
I'm Emmanuel Tochukwu, software developer. I have experience writing smart contract on Starknet. I would love to work on this project.

**Comment by saimeunt** [comment]
Hey, I'm a returning contributor having previously worked on testing gostarkme, I think this can be completed in half a day.
