### ISSUE TITLE
[feat] Add new asserts to set_contact_handle

### ISSUE THREAD

**Issue by EmmanuelAR** [web3wagers/gostarkme#255]
### This issue will be part of ODHack10, please apply via Onlydust app
- Add new assert that validate that the caller should be the admins in set_contact_handle method in contracts/src/fund.cairo
- The admins are two (VALID_ADDRESS_1,VALID_ADDRESS_2) constants located in contracts/src/constants/funds/fund_manager_constants.cairo
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue.

**Comment by petersdt** [comment]
Hi, I'm Peter and I'll be working on issue #255.

I estimate this will take 8hrs to complete.

This is how I would tackle this issue:

- First, I'll modify the current `set_reason` method to check for both owner and admin permissions. Already we have the pattern for admin validation in the `set_state`method, so I will follow a similar approach.

- Get both admin addresses using `contract_address_const`

- Modified assert to check if caller is either:
      - The fund owner OR
      - Admin 1 (VALID_ADDRESS_1) OR
      - Admin 2 (VALID_ADDRESS_2)

**Comment by mayasimi** [comment]
Hi, I'm  and I'll be working on issue #255.

I estimate this will take 2hrs  to complete since the test issue depend on this task.

This is how I would tackle this issue:
- I'll add validation for both admin addresses using `contract_address_const`
- Modify the assert to check if caller is either:
     The fund owner || Admin 1 (VALID_ADDRESS_1) || Admin 2 (VALID_ADDRESS_2)

**Comment by MrRoudyk** [comment]
Could I grab this task? My profile onlydust https://app.onlydust.com/u/MrRoudyk

**Comment by Tzienom** [comment]
Hello, I'm Gabriel and I'd love to work on issue #255.

**Comment by 0xprivateChaos** [comment]
Hi, I'm Aman, and I'll be working on issue #[Issue Number].

This is how I would tackle this issue:

1. Add a new assertion in the ```set_contact_handle``` method to validate that the caller's address matches ```VALID_ADDRESS_1``` or ```VALID_ADDRESS_2```.
2. Import the constants ```VALID_ADDRESS_1``` and ```VALID_ADDRESS_2``` from ```fund_manager_constants.cairo```.
3. Update tests to include scenarios where the caller is one of the admins or an unauthorized user.

**Comment by Unickhub** [comment]
This will be really cool, Can I take this issue?

**Comment by mimisavage** [comment]
Can I start working on this?

**Comment by manlikeHB** [comment]
Hi, I am a Cairo developer and a returning contributor, can I work on this?

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo project like chainevent etc .   please /assign  this issue .
Thank You

**Comment by ShantelPeters** [comment]
Could I take over this issue?

**Comment by akintewe** [comment]
Hi, I'm akintewe and I'll be working on issue
I have experience in cairo and typescript 

I My ETA is > 24hrs to complete.

I would tackle this issue with these steps:

i will first locate set_name: Find the method in contracts/src/fund.cairo.
Access Admin Constants: Use VALID_ADDRESS_1 and VALID_ADDRESS_2 from fund_manager_constants.cairo.
I will also check and makle sure the tests are perfect 
I am a new contributor, happy to help :)

**Comment by codebestia** [comment]
Can i be assigned this?
I am an experienced blockchain developer with ample experience in building smart contracts and writing test. I believe i am up to the task

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend developer with experience
i would really love to contribute to your project 
kindly assign :)

**Comment by sotoJ24** [comment]
Hello team, greetings, I have knowledge in Cairo and performance tests, stress, bigO algorithm analysis, test speed, clean code, I think I can work on it,

Josué,
De Dojo Coding

**Comment by Emmanex01** [comment]
I’m interested in this one.

**Comment by saimeunt** [comment]
Hey, I'm a returning contributor having previously worked on testing gostarkme, I think this can be completed in half a day.
