### ISSUE TITLE
[test] Add test for new assert in set_name method

### ISSUE THREAD

**Issue by EmmanuelAR** [web3wagers/gostarkme#256]
### This issue will be part of ODHack10, please apply via Onlydust app
- Add new test for the new assert admins in set_name in contracts/src/fund.cairo.
- This issue can be work once the #252  is done
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue.

**Comment by Judah04** [comment]
Hi, I'm Judah04 and  I'll like to work on issue #256.

I estimate this will take 5hrs to complete this task. am experience in writing and testing smart contracts in cairo and solidity

This is how I would tackle this issue:
- I will set up addresses for owner, random user and both admins using a setup_address function and would be using contract constants for admin addresses
- The test cases would cover:

    - test_owner_can_set_name: Verifies owner can set name
    - test_admin1_can_set_name: Verifies first admin can set name
    - test_admin2_can_set_name: Verifies second admin can set name
   - test_random_user_cannot_set_name: Verifies unauthorized users cannot set name

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by OWK50GA** [comment]
I'd like to take this issue.
I'm a Cairo Smart Contract Developer adept at writing tests.
ETA - 1 day, once #252 is done

**Comment by Thibrac** [comment]
Can I try solving this issue? I'm newbee but i want to try ! :)

**Comment by No-bodyq** [comment]
Can I jump on this task?

**Comment by mimisavage** [comment]
May I try my hand at this?

**Comment by Benjtalkshow** [comment]
Can I attempt this issue?

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many stark net project and more  .   please /assign  this issue .
Thank You

**Comment by ShantelPeters** [comment]
May I try my hand at this?

**Comment by Michaelkingsdev** [comment]
Could I take over this issue?

**Comment by SoarinSkySagar** [comment]
May I work on this issue once the mentioned issue is resolved, @EmmanuelAR?

I am an experienced cairo dev and a regular contributor at @keep-starknet-strange.

eta: 3 days

**Comment by No-bodyq** [comment]
Hi, I'm Asher and I'll be working on issue #256.

I estimate this will take >24hrs to complete.

This is how I would tackle this issue:

Go through and understand the method being tested and write test for the new assert, taking into account any edge cases

**Comment by akintewe** [comment]
Hello can i be assigned this issue, i am a new contributor with experience in Cario and typescript, would love to work on this , my ETA is >20 Hours and ill create a draft PR in 17 hours time. Thank you for this opportunity. :)

**Comment by sotoJ24** [comment]
Hello team, greetings, I have knowledge in Cairo and performance tests, stress, bigO algorithm analysis, test speed, clean code, I think I can work on it,

Josué,
De Dojo Coding

**Comment by saimeunt** [comment]
Hey, I'm a returning contributor having previously worked on testing gostarkme, I think this can be completed in half a day.

**Comment by Kaminar-i** [comment]
Can I work on this, please?

**Comment by LazarusAA** [comment]
Hi! I'm Alvaro Lazarus, a developer from Dojo Coding ⛩️. I enjoy creating targeted tests to ensure code reliability, and I’d be happy to contribute by adding a test for the new assert in the ```set_name``` method.

My workflow:

- Write a test to cover the new assert in the ```set_name``` method
- Ensure the test checks edge cases and expected failures
- Verify the test improves overall coverage and maintains reliability

ETA: 48 hrs

**Comment by Gianfranco99** [comment]
Hello, I can solve this issue easily, I have already been contributing to this project and I would like to continue being part of it!

**Comment by petersdt** [comment]
Mind if I take this issue?

**Comment by aguilar1x** [comment]
Good morning, My name is Matias Aguilar, I am a software development engineer with 1 year of experience in backend and some Frontend. I have worked on several issues about testing and implementing functions in practice so I already have an idea of ​​how to implement each thing and make it understandable and clean at the same time. I am a member of Dojo Coding, and I would really love to participate in the project with this issue.

## Implementation and solution to the problem
I am going to cover certain important points for the implementation of the test, without leaving aside how I would start working on it.

## 1. Fork Repository and create code in the same

 1 The Fork of the main repository of the project will be created to my normal repository.
 2 The test will begin to be implemented in accordance with the function linked to the test requirement
 3 The steps of everything will begin to be implemented.

## 2. Test resolution

 - The implementation of the references will be carried out to complete the test
 - The various scenarios will be considered to complete the contract test
 - The necessary commits for resolution will be sent.
 - The recommendations given by the maintainer will be accepted 

Features to consider:

    1. Test for the new assert admins in set_name in contracts/src/fund.cairo.


## 3. Clean execution of a PR

The bases will be explained to be able to make a PR in the best and cleanest way possible.

## Questions and recommendations

I am waiting for questions and recommendations on how you would like to implement the test, so if you need any changes or implementation of something or another.

**Comment by NueloSE** [comment]
Is this issue still available?

am experienced in writing and tesing smart contracts in cairo.

depending on th implementation of #252 i will ensure to test all edge case related to`set_name` kindly assign me eta <= 8hrs

**Comment by htiennv** [comment]
Hey, I would like to work on this issue. Thanks!

**Comment by mimiprosper** [comment]
I’d like to work on this.  Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 4 days.

**Comment by bruhhgnik** [comment]
i can do this, within 24 hours

**Comment by wheval** [comment]
May I take this issue on?

**Comment by aurlic** [comment]
May I be assigned to this?

**Comment by tekkac** [comment]
Ahoy, I'm tekkac and I'll be working on issue #256
I estimate this will take 1-2 days to complete.
The test is straight-forward, one issue is blocking but shouldn't be a problem.

**Comment by GideonBature** [comment]
May I take care of this?

My name is Gideon Bature, a Software Engineer with experience building Starknet based smart contracts, using Cairo, writing both unit and integration tests. If given this issue, I will send my first PR within 24 hrs right after issue #253 is completed. 

Thank you!
