### ISSUE TITLE
[test] Add test for new assert in set_contact_handle method

### ISSUE THREAD

**Issue by EmmanuelAR** [web3wagers/gostarkme#259]
### This issue will be part of ODHack10.0, please apply via Onlydust app
- Add new test for the new assert admins in set_contact_handle in contracts/src/fund.cairo.
- This issue can be work once the #255 is done
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue.

**Comment by raizo07** [comment]
Could I be assigned to this? I'm a software developer with over four years of experience

**Comment by OWK50GA** [comment]
I'd like to take this issue.
I'm a Cairo Smart Contract Developer adept at writing tests

**Comment by Emmanex01** [comment]
I would love to work on this?

**Comment by No-bodyq** [comment]
Can I attempt this issue?

**Comment by ncoquelet** [comment]
Could I be assigned to this?

# Presentation

Hello, I'm senior developer, comfortable with Typescript, React/Vite/Next, testing, CI/CD, docs and I'm a beginner on Cairo (starklings 100% and NodeGuardians “Entering Cairo”, “Thinking in Cairo”, “Vanity Address”, and I continue).
I'm rigorous and diligent, I'm used to contributing my skills to projects and can move really quickly.

# How do I resolve this issue?

I will Implement specifications.

- add new test as mentioned
- can take #255 too to go faster

Contributors guide checked !

**Comment by mimisavage** [comment]
May I handle this issue?

**Comment by akintewe** [comment]
Hello can i be assigned this issue, i am a new contributor with experience in Cario and typescript , would love to work on this , my ETA is >22 Hours and ill create a draft PR in 17 hours time. Thank you for this opportunity. :)

**Comment by GideonBature** [comment]
Let me handle this issue!

My name is Gideon Bature, a Software Engineer with experience building Starknet based smart contracts, using Cairo. If given this issue, I should be able to send my first PR within 48 hrs right after issue #255 is completed. 

Thank you!

**Comment by Birdmannn** [comment]
Please let me be assigned this. I've just had one non-code contribution. I can handle this, I'm familiar with cairo and starknet as a whole. I'll create a new test in the test file in the test folder to check that function, and ensure that there no no further bugs on that function.

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many stark net project and more  .   please /assign  this issue .
Thank You

**Comment by ShantelPeters** [comment]
I'd like to take this issue.

**Comment by ChrisFernandezVivas** [comment]
Hi, I'm from dojo coding  and I'll be working on issue  

I estimate this will take 4 days to complete.

This is how I would tackle this issue:


1- declare a test variable
2- try figure out the set_contract_handle
3- start write test 
4- testing the new instance

**Comment by Michaelkingsdev** [comment]
Could I grab this task?

**Comment by ryzen-x** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You

**Comment by Kom02** [comment]
Hi, My name is Kevin Obando, a full stack junior developer with 2 years of experience from Costa Rica. I am starting in this community and I want to help in this project.

**Comment by Supa-mega** [comment]
May I take care of this?

**Comment by ikezuby2012** [comment]
hello, can i be assigned this issue?

my name is nnubia nzube, i'm a software developer with experience in writing smart contract using cairo, i would like to write the test for the contract, my ETA is within 24 hours.

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend developer with experience
i would really love to contribute to your project 
kindly assign :)

**Comment by sotoJ24** [comment]
Hello team, greetings, I have knowledge in Cairo and performance tests, stress, bigO algorithm analysis, test speed, clean code, I think I can work on it,

Josué,
De Dojo Coding

**Comment by saimeunt** [comment]
Hey, I'm a returning contributor having previously worked on testing gostarkme, I think this can be completed in half a day.

**Comment by Kaminar-i** [comment]
please, can have the opportunity of working on this?

**Comment by htiennv** [comment]
I'd like to handle this task. Thank you!

**Comment by mimiprosper** [comment]
I'd like to take this issue.  Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 4 days.

**Comment by bruhhgnik** [comment]
i can do this, eta: 24 hours

**Comment by Aditya-040** [comment]
I’d like to work on this.

**Comment by hossamanany** [comment]
I’d like to resolve this.

**Comment by Thibrac** [comment]
Could I be assigned to this?

**Comment by Rayguti** [comment]
Description:
This issue involves creating a new test for the assert_admins function in the set_contact_handle method located in contracts/src/fund.cairo. The task is a follow-up to issue #255 and will ensure robust testing for the new implementation. Contributors must complete the prerequisite issue before starting this one.

Why I’m Interested:
With experience in TypeScript and a growing understanding of Cairo, this issue aligns perfectly with my skills and interests. It presents an opportunity to engage with smart contract testing in Cairo while applying structured testing principles. I am eager to contribute to ODHack10.0 and explore deeper integrations between blockchain and development environments.

Proposed Approach:

    Understand the Context:
        Review the implementation of set_contact_handle and the changes introduced in issue #255.
        Analyze the role of assert_admins to identify edge cases and scenarios for the test.

    Test Implementation:
        Write test cases to cover all possible outcomes for assert_admins, including:
            Valid admin assertion.
            Invalid admin scenarios (e.g., unauthorized users).
            Boundary conditions for admin roles.
        Use TypeScript and Cairo testing frameworks to validate contract behavior.

    Adhere to Guidelines:
        Follow the contributor’s guide to align with project standards and practices.
        Ensure test documentation and structure are consistent with existing test suites.

    Collaboration:
        Coordinate with contributors working on issue #255 to clarify dependencies and avoid conflicts.
        Seek feedback from maintainers during development to refine the test implementation.

Outcome:
A comprehensive test for the assert_admins function will be added to the repository, ensuring the reliability of the set_contact_handle method and contributing to the project’s overall robustness.

Application Process:
This issue is part of ODHack10.0. Interested contributors should apply through the Onlydust app after reading the contributor's guide.

**Comment by Yunusabdul38** [comment]
Hi, I'm yunus abdul and I'll be working on issue #259.

I estimate this will take 50  minute to complete.

This is how I would tackle this issue:
1- i will fork and  clone the repo to my machine
2- i will add a new test to assert admins for set_contact_handle method
3-i will fulfill all rules in contributors guide before making a pull request

**Comment by Yunusabdul38** [comment]
Hi, I'm yunus abdul and I'll be working on issue #259.

I estimate this will take 5 hours to complete.

This is how I would tackle this issue:
1- i will fork and  clone the repo to my machine
2- i will add a new test to assert admins for set_contact_handle method
3-i will fulfil all rules in contributors guide before making a pull request

**Comment by abdegenius** [comment]
I'd like to handle this task.
