### ISSUE TITLE
[feat] Welcome page

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#26]
Create the necessary modules and pages to replicate the welcome page of this project, take a look at the README.md to see the Figma design we currently have.

**Comment by arturch2011** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I'm currently working on the front-end of https://www.metronome.finance/ 

### How I plan on tackling this issue
I will create a components directory, a welcome page directory inside it and the components for the top bar, form and I will place these components on the root page or any page you want!

**Comment by adrianvrj** [comment]
Hi @arturch2011 unfortunately we do not have enough resources to pay our contributors yet, would you still like to participate solving this issue?

**Comment by arturch2011** [comment]
Of course. Just looking to add some contributions to my profile and see how
only dust works !

Em qua., 14 de ago. de 2024 13:13, ADR!AN ***@***.***>
escreveu:

**Comment by adrianvrj** [comment]
Nice! Feel free to contact me or @EmmanuelAR if you have any doubts, also make sure to read our contributor guidelines and take a look at the Figma design. Ty very much.

**Comment by adrianvrj** [comment]
If possible, please use Helvetica font @arturch2011

**Comment by arturch2011** [comment]
I've seen figma, do you know if the Helvetica font is on Google fonts or if there is a similar font there, I also want to know if the welcome page will be the root page or do I create a separate page !

**Comment by adrianvrj** [comment]
It is not in Google fonts, I think we will need to look for a way to set it up. And yes, it will be the root page.

**Comment by arturch2011** [comment]
OK! I think I'll do everything later today
