### ISSUE TITLE
[feat] Check connection network

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#277]
### This issue will be part of ODHack8.0, please apply via Onlydust app
- Create a variable in the .env file called network ex: ```NETWORK = sepolia```.
- When the user connects to the blockchain, make sure the network is correct according to the .env file.
- **Do not upload changes to the .env.example file nor config files please.**
- If the user is not connected to the correct network, disable the voting and donating btns.
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue.

**Comment by Abeeujah** [comment]
Hi, I'm Abeeujah, a Full Stack Engineer, Proficient in Js/Ts, Rust, Go and Cairo, I'll be working on issue #277

I estimate this will take 6Hrs to complete.

This is how I would tackle the issue:
- create the NETWORK variable in the .env file
- read the env file to know the network the user is connecting to, to better inform or guide their wallet to switch to mainnet or sepolia
- would omit including it in .env.example, config as specified in the issue description.

**Comment by Benjtalkshow** [comment]
Could I try solving this?

**Comment by blessingbytes** [comment]
pls can i work on this

**Comment by josephpdf** [comment]
Hi! @adrianvrj 
I'm Joseph Poveda, I'm a member of the Dojo Coding community.
A bit about my background is that I'm just starting out with Only Dust and I want to contribute as much as I can to the project. My knowledge of different programming languages ​​will allow me to better solve problems.
To solve this issue I will:
1. **Environment Variable Setup**:
   - Add a variable `NETWORK` in the `.env` file (e.g., `NETWORK=sepolia`) to specify the expected blockchain network.
   - Ensure `.env.example` and other config files remain unchanged.

2. **Network Validation**:
   - Implement a check to confirm the user's connected blockchain network matches the `NETWORK` variable.
   - Use appropriate methods from the blockchain connection library (e.g., Web3.js, ethers.js) to retrieve the user's network details.

3. **UI Update**:
   - Disable the "voting" and "donating" buttons if the user is not connected to the correct network.
   - Provide feedback or a message prompting the user to switch networks.

4. **Testing and Submission**:
   - Test the functionality across scenarios (e.g., correct and incorrect networks).
   - Submit changes as a pull request for review.

**Comment by adrianvrj** [comment]
@Abeeujah assigned! Take in account that ODHack finishes this weekend!
