### ISSUE TITLE
Implement dark mode

### ISSUE THREAD

**Issue by SimplementeCao** [web3wagers/gostarkme#286]
Gm! I would love to implement a dark mode, would it be possible ?

**Is your feature request related to a problem?**
Note that only light mode is available

**Describe the solution you would like**
I would love to implement a dark mode

**Describe the alternatives you have considered**
Add a button to be able to choose between dark/light mode

**Comment by adrianvrj** [comment]
this is a feature we will need in the future, but we will use it for an odhack, thanks for pointing it out!
