### ISSUE TITLE
[docs] Add information about the project's setup in the documentation

### ISSUE THREAD

**Issue by renzobanegass** [web3wagers/gostarkme#30]
The documentation is missing information about: 

- How to build the Cairo project.
- The specific scarb version that has to be used (2.6.5)
- Formatting tools used (like trunk) and how to run them before making a commit.
- Add how to run tests (this needs #13 or #14 first)

asdf could be recommended to manage the version of scarb in the project.
a step to step with CLI commands in the contributor guidelines would be nice to have for newcomers.

This is a proposal, please tell me what you think.

**Comment by adrianvrj** [comment]
@renzobanegass looks good, I would probably add the steps to the README.md file tho, would you like to work on it?

**Comment by renzobanegass** [comment]
Sure, I can take it after finishing the tests

**Comment by kateberryd** [comment]
Hi @adrianvrj If this issues is still open I would love to work on it

**Comment by adrianvrj** [comment]
Hello @kateberryd any progress on this?

**Comment by kateberryd** [comment]
Hi @adrianvrj, Yes I made progress. I will open a PR soon

**Comment by EmmanuelAR** [comment]
heyyyy @kateberryd any update?

**Comment by ShubhamPatilSp** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I’m Shubham Patil, a full-stack developer experienced in building web applications using the MERN stack. My key projects include:

Traveller: A travel platform inspired by Airbnb, featuring dynamic user authentication and robust data handling. You can explore it here: https://traveller-node.onrender.com/listings.
Portfolio Website: A Next.js-based portfolio showcasing projects with advanced UI components and interactive elements. Check it out at: https://my-portfolio-mauve-one.vercel.app/.
VirtualR: A tool for designing VR environments with a drag-and-drop interface and real-time collaboration. Visit it here: https://virtualr-main-git-main-shubhampatilsps-projects.vercel.app/.

### How I plan on tackling this issue
I approach problems by breaking them down into manageable parts to identify core issues. Using my expertise in the MERN stack, I prioritize creating efficient, scalable, and user-friendly solutions. I leverage tools like Passport.js for authentication, Joi for validation, and Cloudinary for media management. I believe in an iterative process with continuous testing and feedback to ensure the solution is robust and optimized.

**Comment by danielcdz** [comment]
@EmmanuelAR @adrianvrj is this available? 👀 if so I can help you with this one

**Comment by adrianvrj** [comment]
@danielcdz yes it is, feel free to join our discord server do discuss certain things like the tooling versions, ty for the interest!
