### ISSUE TITLE
[CI] Add workflow to deploy frontend

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#37]
Make sure to read our [contributors guide](https://github.com/web3wagers/gostarkme/blob/main/CONTRIBUTORS_GUIDE.md) before you ask for an issue.

Add the necessary steps to build and test the frontend changes.

To solve this issue you will have to add a .yaml file to .github/workflows.

**Comment by BDCoy** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hello, I’m Brayan. With over  3 years of experience in development, I am passionate about contributing to open-source projects and currently expanding my skill set with Rust, Cairo, and Solidity as part of my involvement with Dojo Coding. My recent role as a Full Stack Developer allowed me to specialize in a range of technologies including React, NextJs, Node.js, JavaScript, TypeScript, Docker, among many others. I am eager to apply my extensive experience and newly acquired skills to new challenges and innovative projects.

### How I plan on tackling this issue
I've reviewed the project setup, which uses Next.js, React, and TailwindCSS. I'd like to contribute by adding clear steps to build and test frontend changes. I'll document the necessary commands for building and testing in the README.md or relevant files, ensuring they work across different environments. This will help streamline the process for other contributors. Please confirm if I can proceed.

**Comment by adrianvrj** [comment]
Hi @BDCoy, this is not a documentation issue, this is a CI workflow issue.
