### ISSUE TITLE
Testing Donators Manager Contract

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#43]
Add necessary code to test all donators manager contract functionalities

**Comment by EmmanuelAR** [comment]
I can work this too

**Comment by ooochoche** [comment]
@adrianvrj can this be assigned to me

**Comment by kateberryd** [comment]
Hey @adrianvrj I would love to work on this

**Comment by adrianvrj** [comment]
@EmmanuelAR lets keep one active issue per contributor.

@ooochoche @kateberryd could you add more context on how you plan tackling this issue and the time it could take for you to finish the task?

**Comment by ooochoche** [comment]
@adrianvrj I'll implement a setup function that deploys the Donators Manager contract and retrieves the dispatcher. I'll use this to perform the following tests:

- Verify that the contract owner is correctly set to the deployer's address.
- Confirm that new donators are added correctly.
- Ensure that donators are accurately retrieved from the contract's storage.

**Comment by adrianvrj** [comment]
@ooochoche assigning you since you provided a good description

**Comment by EmmanuelAR** [comment]
hey @ooochoche any update?

**Comment by DiegoB1911** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I'm a Full Stack Developer with two years of experience. I'm also an active member of Dojo Coding, where I'm expanding my skills in Cairo and Web3 technologies.  I'm eager to learn, contribute, and be part of this project.

### How I plan on tackling this issue
To solve this issue, I would:

1. Create a setup function to deploy the contract and initialize any necessary data.
2. Create a test to verify that the newDonator function is adding new donators correctly.
3. Create a test to verify that the getDonatorByAddress function is returning the donator's address correctly.
4. Perform a final verification to ensure that the tests are comprehensive.
5. Document the code.

**Comment by ShubhamPatilSp** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I’m Shubham Patil, a full-stack developer experienced in building web applications using the MERN stack. My key projects include:

Traveller: A travel platform inspired by Airbnb, featuring dynamic user authentication and robust data handling. You can explore it here: https://traveller-node.onrender.com/listings.
Portfolio Website: A Next.js-based portfolio showcasing projects with advanced UI components and interactive elements. Check it out at: https://my-portfolio-mauve-one.vercel.app/.
VirtualR: A tool for designing VR environments with a drag-and-drop interface and real-time collaboration. Visit it here: https://virtualr-main-git-main-shubhampatilsps-projects.vercel.app/.

### How I plan on tackling this issue
I approach problems by breaking them down into manageable parts to identify core issues. Using my expertise in the MERN stack, I prioritize creating efficient, scalable, and user-friendly solutions. I leverage tools like Passport.js for authentication, Joi for validation, and Cloudinary for media management. I believe in an iterative process with continuous testing and feedback to ensure the solution is robust and optimized.

**Comment by adrianvrj** [comment]
@DiegoB1911 assigned!

**Comment by DiegoB1911** [comment]
Thanks! I'll start working on it.
