### ISSUE TITLE
[CI] Add snforge test to CI pipeline

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#64]
**Is your feature request related to a problem? Please describe.**
Currently we do not test changes to the contracts code.

**Describe the solution you'd like**
A new step that runs the tests for the contracts.

Before asking for issues to be assigned to you, please read our contributors guidelines.

**Comment by jorgezerpa** [comment]
Hi! @adrianvrj, I'm Jorge

I saw this this issue and make a quick demo [here](https://github.com/jorgezerpa/gostarkme/blob/ci/contracts-testing/.github/workflows/contracts_testing.yml). I created a ".github/workflows/contracts_testing.yml" file, where I put the steps for:
1. Install scarb
2. Install snfoundry
3. Build the contracts
4. Run tests with "snforge test"

Please check and let me know if it is what you are looking for so I can submit a PR🚀

Of course I'm open to any correction-modification you would like to make🙌 maybe trigger just on an specific branch, an specific action, etc

**Comment by KevinMB0220** [comment]
Hello @adrianvrj,  I'd like to work on this issue.

I propose adding a new step in the CI pipeline that automatically runs the snforge tests for the contracts. This will ensure that any changes to the contract code are tested as part of the CI process, helping to catch potential issues early.

I have experience working with Cairo, and I'm currently participating in Dojo Coding, which has further strengthened my skills. Please let me know if there are any specific requirements or considerations I should be aware of before I begin.

**Comment by bitfalt** [comment]
Hi! My name is Daniel. I would love to take on this issue to implement the testing feature in the CI pipeline, to ensure everything works perfectly.

**Comment by EmmanuelAR** [comment]
letsss gooo mate @bitfalt

**Comment by adrianvrj** [comment]
@bitfalt nice to have you here, you can join our [discord channel](https://discord.gg/sEpnC6JB2U) if you have any questions.

**Comment by bitfalt** [comment]
love being part of the project, will do immediately @adrianvrj!
