### ISSUE TITLE
Add Donator contract

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#7]
Add a donator profile contract, this contract should be unique for every address and have the following attr:
- owner
- total_donations
- level

The reason we want to include this is because we want active user with the most level to have priorities later when they need a funding, making them appear on top of the fundings lists or appear as promoted in certain parts of the lists, also making the necessary votes less for them.

**Comment by adrianvrj** [comment]
@EmmanuelAR would you like to take this?

**Comment by EmmanuelAR** [comment]
Sure

**Comment by EmmanuelAR** [comment]
PR #38
