### ISSUE TITLE
[docs] Add Frontend Setup Documentation

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#84]
### This issue will be part of ODHack8.0, please apply via Onlydust app
- Local Deployment: In the frontend folder of the project, clearly detail the steps required to run it in a local environment.
- Production Deployment: In the frontend folder of the project, clearly detail the steps required to run the project in production.
- To address this issue, we recommend that the person in charge start by setting up the local environment step by step, documenting the process, any potential questions about the project, and maintaining continuous communication with the development team (via the Discord channel) or directly contact Adrian via [telegram](https://t.me/adrian_vrj).
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue.

**Comment by od-hunter** [comment]
Hi @adrianvrj , please I’d love to work on this once od hack starts.

**Comment by Jemiiah** [comment]
@od-hunter i have great track record on docs issue can I work on this issue

**Comment by martinvibes** [comment]
hello @dmirgaleev i am a frontend dev and technical writer
please can i work on this issue :) and would love to be a contributor

**Comment by sanieni6** [comment]
Hey @adrianvrj. i'm gonna be glad to work on this😄 
## My approach:
I’ll start by creating a reusable Navbar component using Next.js and TypeScript, following the design provided. I will ensure that the component structure is modular and adheres to best practices, making it easy to integrate functionality in the future.

**Comment by PabloVillaplana** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I am a Full Stack developer with 6 years of experience in the industry, I am super excited to be able to contribute to Web 3 projects, this to continue paving my way as an Open Source Contributor. I am from Dojo Coding Community

### How I plan on tackling this issue
I can help with this documentation and collaborate on this incredible social impact project. 🚀🇨🇷

**Comment by sanieni6** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hi! My name is Luis Sanchez, and I’m a Frontend Developer with 3 years of experience, specializing in TypeScript, React, and Next.js.
dojo coding member, i am gonna be glad to contribute, pura vida

### How I plan on tackling this issue
I’ll clone the repository and carefully follow the existing setup instructions to identify any gaps or unclear steps in the local deployment process. I’ll document each step clearly and address any issues that arise during the setup.

this is simple i'll promese i'll be carefull

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I am a technical writer

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
i am currently taking a cairo bootcamp and am experienced using Js and typescript for type safety kindly assign me this task

### How I plan on tackling this issue
Set Up Local Environment:
I will start by setting up the project locally step by step in the frontend folder and
document each step clearly, noting any issues or questions that arise.

Document Local Deployment:
Write detailed instructions on how to run the project in a local environment, including dependencies and commands.

Set Up Production Environment:
Similarly, set up the project for production.
Document the steps for running the project in production.

ETA <48hrs

**Comment by pheobeayo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I am a Web3 frontend developer and Technical writer skilled in JavaScript, Typescript and documentation. My documentation skills are clearly visible in Readme files of my repositories.

### How I plan on tackling this issue
I will do this documentation in the following steps.
-I will run the app successfully locally
- I will take note of all the steps required for me to run it successfully
- I will document these steps in the documentation for any user to easy run the app.

**Comment by deeseeker** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hi, I'm Qudus Adeyemi, a front-end developer with 2 years of experience. I had the opportunity to contribute to the previous OD Hackathon, where I improved the Starknet React documentation and developed a useWatchAssets hook to enhance wallet tracking functionalities. I enjoy learning and tackling new challenges, and I see this issue as a great way to deepen my understanding of Web3 technologies while contributing to the Gostarkme project.

For the issue, I estimate it will take around 1-2 days to complete, and I'm excited to dive into the task and collaborate with the team!

### How I plan on tackling this issue
I have run the code in dev and production mode. My next steps of tackling this issue is to document clearly how I spin up the project and communicate with Adrian or any other member of the process.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hi @adrianvrj,

I’m Benjamin, a JavaScript developer with 4 years of experience and over 18 contributions on OnlyDust | https://app.onlydust.com/u/Benjtalkshow. I love creating responsive and user-friendly interfaces with tools like Next.js and Svelte, and I’m excited about the opportunity to work on the deployment documentation for Go Stark Me project.

### How I plan on tackling this issue
For this task, I’ll be putting together clear and easy to follow instructions for running the project both locally and in production, right in the frontend folder. I know how important good documentation is especially for helping everyone get on board smoothly and ensuring that we’re all on the same page. I take pride in writing documentation that’s straightforward and helpful, so I’m looking forward to diving into this.

I’ll kick things off by setting up the local environment step by step, carefully noting down each part of the process. I’ll make sure to highlight any common questions or issues that might pop up, along with some tips to make things easier. Plus, I’ll keep the lines of communication open with the development team through Discord and will be available to chat directly with you on Telegram whenever needed.

Once I’ve got the documentation ready, I’ll share it with you for feedback and make any tweaks necessary. I can’t wait to contribute to this project and help make our deployment process as smooth as possible for everyone involved.

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hello can I be assigned this please? I am a blockchain developer and I'm also good at documentations. Below are some of the documentations i have done that were merged:

https://github.com/dojoengine/book/pull/308#event-13866062226

https://github.com/keep-starknet-strange/joyboy/pull/143#event-13034455918,

https://github.com/horuslabsio/Starknet-Scaffold/pull/94#event-13007360671.

Some of my documentations outside GitHub:

https://t.co/ZgK0ccPZpw,

https://t.co/GnBqVQPECz.

Please I’m ready to work, assign me please.

### How I plan on tackling this issue
I'd do exactly as instructed, Please assign me. I'm ready to work.

**Comment by abdegenius** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I am a skilled fullstack developer with a wealth of experience in both frontend and backend JavaScript as well as my knowledge of Rustlang, With a solid foundation in testing,I have mastered frameworks like Mocha, Chai, and Jest to ensure robust, reliable code in every project. In addition to traditional web development, I have a strong background in blockchain technology, with hands-on experience in Solidity for Ethereum-based smart contracts. Moreover, I have delved into the emerging world of StarkNet, working with Cairo, a cutting-edge language tailored for STARKs, making them a versatile developer capable of bridging both traditional and decentralized web applications.


### How I plan on tackling this issue
I write write a really simple to understand and few step guide that is well details and properly captures every necessary steps to setting up the frontenf, from libraries to tools needed, to commands for running on various environments

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I am frontend / blockchain developer with experience in the field  UI/UX , i will like to work on this issue 

### How I plan on tackling this issue
 i will approach this issue by creating a new page at the route /app/myprofile/{useraddr in the Next.js application, ensuring it serves as the user’s profile page without the navbar, as it will be added separately. The page should accept the user's address as a parameter and focus exclusively on replicating the design elements from the Figma prototype, without implementing any functionality. Familiarity with TypeScript and adherence to the contributor's guide are required for this task.

**Comment by MPSxDev** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hello, I am Manuel, a process engineer and web3 developer. I have participated in Starknet Bootcamps, ETHGlobal  and am an Elite winner of Speedrunstark. I have a high capacity to solve problems. I am a member of the DojoCoding community.
I hope this issue is assigned to me. I am available to work immediately to achieve what is required in the shortest time possible.

### How I plan on tackling this issue
I would love to take this issue and do everything requested.

**Comment by fabrobles92** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
My name is Fabricio Robles, I work as a full stack dev since 3 years ago. Also I have been involved in web3 where I have contributed successfully to projects like dojo engine, Concrete and Kakarot. I have experience working with NextJS, npm, pnpm, node and plain react I am sure that experience would help me delivering a quality solution for this project

### How I plan on tackling this issue
- Fork the repo
- Install dependencies
- Run it locally with the scripts declared in package.json
- Gather the steps in a detailed way
-  Document
- PR

**Comment by DiegoB1911** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I'm a Full Stack Developer with two years of experience. I'm also an active member of Dojo Coding, where I'm expanding my skills in Cairo and Web3 technologies. I'm eager to learn, contribute, and be part of this project.

### How I plan on tackling this issue
To solve this issue, I would approach it as follows:

Local Deployment:
I will create clear, step-by-step instructions to set up the project in a local environment. This will include:

Cloning the repository.
Installing necessary dependencies.
Setting up environment variables.
Running the local development server.
Troubleshooting any common issues (e.g., package conflicts, missing environment variables).
I will thoroughly test the local deployment process myself and ensure that all steps are clearly documented for other contributors.

Production Deployment:
I will provide comprehensive guidance on how to build the frontend for production. This will include:

Running the build process to generate optimized production files.
Configuring environment variables and any production-specific dependencies.
Setting up hosting and deployment instructions (e.g., deployment to a cloud service or static hosting).
Ensuring that the production build is optimized and runs seamlessly.

**Comment by jsandinoDev** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hi I'm a fullstack developer from Costa Rica, member of Dojo Coding I have experience working with JavaScript, React, TypeScript, Cairo, Next.js, Node.js.


### How I plan on tackling this issue
1 - I will start configuring the local environment by understanding and analyzing each step.
2- Create the documentation of how to run the project in a local environment, with all the commands, possible problems and solutions.
3- Create the documentation of how to run the project in a production environment
