### ISSUE TITLE
[docs] Add Backend Setup Documentation

### ISSUE THREAD

**Issue by EmmanuelAR** [web3wagers/gostarkme#86]
### This issue will be part of ODHack8.0, please apply via Onlydust app
- Explain the necessary steps to install Scarb.
- Explain the installation process for the required version to run the project (2.6.5).
- Explain the commands for compilation, formatting, and testing.
- How to integrate a new contract.
- How to integrate testing for a contract.
- Add the UML diagram that is in the project’s README.
- Explanation of code formatting standards (comments).
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue.

**Comment by Jemiiah** [comment]
I

**Comment by martinvibes** [comment]
hello @dmirgaleev i am a frontend dev and blockchain developer
please can i work on this issue :) and would love to be a contributor

**Comment by Gift-Naomi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I am a web3 developer/ Technical writer


### How I plan on tackling this issue
I have experience in a lot of open source contributions especially in making Documentation
Here are some of the merged docs I’ve written
Flex-NFT-Marketplace/Flex-Marketplace-Contract@fc28412
https://hackmd.io/@xZ4BOZ5TTTy1I0ZQHXFOkg/rkFBcGgAC

**Comment by raizo07** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hello @adrianvrj I'll like to be assigned to work on this. 

I'm a software Dev with over four years experience and have worked on a couple of projects here.

### How I plan on tackling this issue
Here is my Profile
https://app.onlydust.com/u/raizo07

**Comment by GoSTEAN** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged

I have a strong background in Solidity, smart contract development, and blockchain technology. Additionally, I have experience in Rust and building CLI tools, making me well-versed in working with decentralized protocols. My skills in smart contract integration, testing, and deployment will help streamline this project.


### How I plan on tackling this issue

I would first install the necessary tools, like Scarb, and ensure the correct environment setup. Then, I would break down the project requirements, starting with contract integration and testing. I’d follow best practices from the contributor’s guide, use modular contract development, and write efficient tests while adhering to code formatting standards.
