### ISSUE TITLE
Add Nextjs Skeleton

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#9]
Initialize a Nextjs project and refactor the contracts src files so now the src dir stays inside another dir called contracts, configure tailwind in the Nextjs app
Project structure should stay like this:

gostarkme
----------- contracts
--------------------- src
------------------------ lib.cairo
-----------frontend
-------------------- nextapp

**Comment by NeelContractor** [comment]
hey i came across the your project its is some language i don't know and i was looking for issue to contribute to. i have a question are you converting your project to nextjs?.

**Comment by adrianvrj** [comment]
> hey i came across the your project its is some language i don't know and i was looking for issue to contribute to. i have a question are you converting your project to nextjs?.

hi, no we are not, we use cairo to develop smart contracts (like a kind of backend) we are looking forward to use next for our frontend
